### DISCUSSION TITLE
Unable to Login After Update to 2.5.2

### DISCUSSION THREAD

**Discussion by chadgriff** [Budibase/budibase#10295] [Help] [answered]
I am running Budibase on Digital Ocean Droplet / Linux Ubuntu / Docker-Compose.  After the upgrade from 2.3.16 to 2.5.2 completes I am unable to log back in after a logout. I get an "Invalid Credentials" message.  The only way I can recover is to restore my droplet from a backup.  I have attempted the upgrade both from within the app as well as using the "docker-compose pull" command. Both methods yield the same behavior post upgrade.  Please advise what may be occurring as I am interested in getting the new improvements to the skeleton loader.

**Comment by andz-bb** [comment]
Hey @chadgriff - does this happen for all users on your instance? Do you use SSO or standard accounts with emails and passwords?

**Comment by chadgriff** [comment]
Andrew,

I can confirm this happens for at least 2 users. I did get a report of a single user still able to login post upgrade.  The only difference between the 2 of us who could not login that I can easily discern is that we have "real" email accounts whereas the single user who could login is actually setup with a "fake" email address. We do not use SSO and make use of regular email based accounts which use passwords.

-Chad

Sent from my iPhone

On Apr 14, 2023, at 4:51 AM, Andrew Thompson ***@***.***> wrote:

﻿

Hey @chadgriff<https://github.com/chadgriff> - does this happen for all users on your instance? Do you use SSO or standard accounts with emails and passwords?

**Reply by chadgriff** [reply]
@andz-bb...replying to ensure you see my edited response above.

**Reply by shogunpurple** [reply]
Hi @chadgriff - thanks for the additional info. So what seems to be happening here is that a server error is being thrown as soon as you try to log in with the standard budibase email users. Since you are self hosted and we can't look, It would be helpful to see the server logs from your instance when you try to log in with the affected users - `docker-compose logs --follow`. An excerpt from that log and potentially any errors that are being thrown there would be very helpful. Thanks

**Comment by chadgriff** [comment]
@shogunpurple I updated my production environment again this weekend (v.2.5.6) to test for "invalid credentials" and experienced the same behavior.  Immediately post upgrade, I am still logged in. But if I intentionally logout and then attempt to log back in, I am still getting the "invalid credentials" message. See attached log files.
[Docker-Compose_Logs_Follow_04222023.txt](https://github.com/Budibase/budibase/files/11302687/Docker-Compose_Logs_Follow_04222023.txt)
[Budibase_Logs_04222023.txt](https://github.com/Budibase/budibase/files/11302688/Budibase_Logs_04222023.txt)

**Reply by chadgriff** [reply]
@shogunpurple  Did the logs I provided yield any insights as to what is causing my authentication issues whenever I update beyond 2.3.16?

**Reply by chadgriff** [reply]
@shogunpurple  I am getting behind on some updates I need to do in my production environment as I cant move forward until I can get this authentication issue resolved. I see errors in the logs but need help to understand what to do about them.  Please advise...

**Reply by shogunpurple** [reply]
Hi @chadgriff - from the logs it seems there are a few issues:
- Your MinIO setup seems to be broken, with this issue https://github.com/Budibase/budibase/issues/8648
- Did you potentially pull a new `.env` file with a different `JWT_SECRET` in the new environment? 

It's hard to debug this one without some kind of reproduction - doesn't seem to have been reported by anyone else either unfortunately.

**Reply by chadgriff** [reply]
Thanks @shogunpurple for the additional info.  I just tested another update event but encountered the same behavior post update as I previously reported.  

Steps to reproduce the error are as follows:
- docker-compose down
- docker-compose pull
- docker-compose up -d
- logout of developer portal
- login to developer portal - receive message "invalid credentials"
- select `reset password` but no email arrives with a reset link

Setup:
Environment : Digital Ocean Droplet / Unbuntu 20.04.5 / Docker-Compose
Current Budibase Version: 2.3.16
Attempted to Update to Budibase Version: There have been several but most recently v.2.6.11

It does not appear a new `.env` file was pulled as the datestamp on my current `.env` is 11/22/2021.

I modified my docker-compose.yaml file with the `minio/minio:RELEASE.2022-10-24T18-35-07Z` statement as reported in issue #8648 and did see in the logs where I was running a MinIO version 6 months old.  However, it did not have any impact regarding the authentication issue

FWIW...I run a development environment on my Windows 10 desktop using Docker Desktop. Just mentioning so you know it is a completely separate instance of Budibase to ensure no there is confusion with my reference to my "production" environment.

**Comment by chadgriff** [comment]
@shogunpurple When comparing logs from my production environment pre-update and post-update, I see the warning
 `MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated` 
in both but I only see the error
 `Unable to use the drive /data: Drive /data: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified` 
in the post-update log files.

Any ideas?

**Reply by shogunpurple** [reply]
That's because you are updating your version of minIO from a version that used the old filesystem, and you already have some data written there.

You can safely ignore the deprecation warnings on the env vars, they won't affect anything.

**Comment by chadgriff** [comment]
Got it...so the minIO update is not at the root cause of my authentication issues. Any suggestions on what additional info I can provide to help zero in on what is causing myself (and certain other users) to lose the ability to login post update?

Are there any clues in here...

```
bbworker              | ERROR [1682216024627] (29 on 0fb98da126db): Invalid credentials
bbworker              |     ForbiddenError: Invalid credentials
bbworker              |         at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
bbworker              |         at /app/dist/api/controllers/global/auth.js:71:18
bbworker              |         at Generator.next (<anonymous>)
bbworker              |         at fulfilled (/app/dist/api/controllers/global/auth.js:28:58)
bbworker              |         at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbworker              | [correlationId=79d85347-3dd8-4466-8f53-9b74e19d9202] [tenantId=default] Trace: [correlationId=79d85347-3dd8-4466-8f53-9b74e19d9202] [tenantId=default] ForbiddenError: Invalid credentials
bbworker              |     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
bbworker              |     at /app/dist/api/controllers/global/auth.js:71:18
bbworker              |     at Generator.next (<anonymous>)
bbworker              |     at fulfilled (/app/dist/api/controllers/global/auth.js:28:58)
bbworker              |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbworker              |     at print (/app/node_modules/@budibase/backend-core/dist/src/middleware/logging.js:86:9)
bbworker              |     at console.trace (/app/node_modules/@budibase/backend-core/dist/src/middleware/logging.js:97:33)
bbworker              |     at /app/node_modules/@budibase/backend-core/dist/src/middleware/errorHandling.js:51:25
bbworker              |     at Generator.throw (<anonymous>)
bbworker              |     at rejected (/app/node_modules/@budibase/backend-core/dist/src/middleware/errorHandling.js:29:65)
bbworker              |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbproxy               | 172.18.0.1 - - [23/Apr/2023:02:13:44 +0000] "POST /api/global/auth/default/login HTTP/1.1" 403 88 "https://portal.danleysoundlabs.com/builder/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "12.51.29.186" response_time=0.360 proxy_host=worker-service:4003 upstream_addr=172.18.0.7:4003
```

Also...any ideas come to mind when considering the SMTP mail function is not working post-update?

**Reply by shogunpurple** [reply]
@chadgriff Those are the same logs you sent me before, no clues. 

Have you tried migrating to a fresh server just to test? https://docs.budibase.com/docs/server-migration

If it works in the new server, I feel like the issue is with your digitalocean setup.

Could you send through your `docker-compose.yaml` and any other additional information about anything you may have changed or have running on your server?

**Reply by chadgriff** [reply]
@shogunpurple Apologies for outdated log paste in my last comment...I must have gotten mixed up on which logs I was looking at.

I have not tried migrating to a new server. Upon reviewing the server-migration document, I worked for a couple of hours to get CLI installed and was unsuccessful. I encountered errors similar to issue #10502. I attempted the CLI install via both npm as well as the binary file download without success.

I reviewed the` .env` file both pre & post upgrade and confirmed the secrets do not change within that file as part of the Budibase update.

Here is my docker-compose.yaml file:

```
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```

Post update I attempted to open one of my apps and received an `Error initializing app overview` message. Additionally, I logged out and attempted a login and received the` invalid credentials` message as well.
![image](https://github.com/Budibase/budibase/assets/15015476/546606a5-03a5-4772-b54d-f11c8e9933bb)





Here is the associated log file for those events:
[Budibase_Logs_05162023.txt](https://github.com/Budibase/budibase/files/11484178/Budibase_Logs_05162023.txt)
