### DISCUSSION TITLE
Problem getting single image running

### DISCUSSION THREAD

**Discussion by reichert** [Budibase/budibase#10639] [Help] [answered]
Hi guys,
I've already setup some times a selfhosted environment using docker-compose with one container per image (minio, couch, app, worker, etc). Now I'm trying to get the single image running but when inspecting with `pm2 status` I keep getting this error and an HTTP 500 is always launched when I try to enter in the /builder or / homepage.

Error generated:
```
0|app  | {"level":"INFO","timestamp":"2023-05-18T12:43:11.551Z","req":{"method":"GET","url":"/","correlationId":"61780ec6-f248-4a63-b500-5b4e63325898"},"res":{"status":301},"responseTime":3,"msg":"request completed"}
0|app  | {"level":"ERROR","timestamp":"2023-05-18T12:43:11.561Z","err":{"type":"TypeError","message":"Invalid URL","stack":"TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:387:5)\n    at URL.onParseError (node:internal/url:565:9)\n    at new URL (node:internal/url:641:5)\n    at getTenantIDFromCtx (/app/node_modules/@budibase/backend-core/dist/src/tenancy/tenancy.js:79:30)\n    at /app/node_modules/@budibase/backend-core/dist/src/middleware/tenancy.js:30:63\n    at Generator.next (<anonymous>)\n    at /app/node_modules/@budibase/backend-core/dist/src/middleware/tenancy.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/@budibase/backend-core/dist/src/middleware/tenancy.js:4:12)\n    at /app/node_modules/@budibase/backend-core/dist/src/middleware/tenancy.js:21:16\n    at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/@koa/router/lib/router.js:368:16\n    at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n    at Object.<anonymous> (/app/node_modules/@budibase/backend-core/dist/src/middleware/authenticated.js:179:24)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/@budibase/backend-core/dist/src/middleware/authenticated.js:31:71","input":"","code":"ERR_INVALID_URL"},"correlationId":"f1284db7-9d3e-49f8-a62e-e9ad3698841b","msg":""}
```

My setup using docker-compose:
```
version: "3"

x-budibase-single: &budibase_single
  image: budibase/budibase:v2.6.11
  restart: unless-stopped
  deploy:
    mode: replicated
    replicas: 1
    resources:
      limits:
        cpus: '2'
        memory: 4096M
      reservations:
        memory: 256M

services:
  app-budibase-single:
    <<: *budibase_single
    container_name: bbsingle
    environment:
      SELF_HOSTED: 1
      MULTI_TENANCY: 1
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      API_REQ_LIMIT_PER_SEC: 1000000
      BASH_SCRIPTING_TIMEOUT: 60
      PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND: 10
      PROXY_RATE_LIMIT_API_PER_SECOND: 20
    volumes:
      - ./data:/data
    networks:
      - postgres
```

My .env below
```
API_ENCRYPTION_KEY=SECRETHIDDEN
JWT_SECRET=SECRETHIDDEN
MINIO_ACCESS_KEY=budibase
MINIO_SECRET_KEY=budibase
COUCH_DB_USERNAME=budibase
COUCH_DB_PASSWORD=budibase
REDIS_PASSWORD=budibase
INTERNAL_API_KEY=budibase

APP_PORT=4002
WORKER_PORT=4003
MINIO_PORT=4004
COUCH_DB_PORT=4005
REDIS_PORT=6379
WATCHTOWER_PORT=6161
BUDIBASE_ENVIRONMENT=PRODUCTION

LOG_LEVEL=debug
ACCOUNT_PORTAL_URL=https://apps.MYDOMAIN.app
API_REQ_LIMIT_PER_SEC=1000000
```

Any thoughts?
