### DISCUSSION TITLE
Table blocks always returns "no rows found" even data already exist

### DISCUSSION THREAD

**Discussion by thanhpd56** [Budibase/budibase#11344] [Help] [answered]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s
  - Budibase v2.8.10
  - App Version: v2.8.10
  - Tenant ID: self hosted

**Describe the bug**
Try to display data of mysql table by table block component, but it always shows "no rows found"

**To Reproduce**
1. In the data connect 1 table of mysql
2. Click create new screen with list view (table block default)
3. Watch the data

**Expected behavior**
The table always show "no rows found". I have tried to connect several tables but the results are the same.
**Screenshots**
Banner table:
<img width="901" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/208e8109-e29f-4d5a-a577-9791bcd307e0">
Banner screen:
<img width="1398" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/0f29128b-92c0-4062-8f75-e7ef24bcd842">

  
**App Export**

**Desktop (please complete the following information):**

**Additional context**
If I change to grid view component, then data is show up as nornal.

**Comment by thanhpd56** [comment]
@melohagan please help.

**Comment by aptkingston** [comment]
@thanhpd56 are you sure you don't have a filter set on your table block?

There are no differences between how the table block and grid block fetch data from a table. If one works, the other will work too, unless you have other settings which are interfering.

![image](https://github.com/Budibase/budibase/assets/9075550/8e253c16-34aa-420c-8e60-5ed4345f0cbe)

Please share screenshots of the settings of your table block.

**Comment by thanhpd56** [comment]
@aptkingston just default one. I don't customize anything.

**Comment by thanhpd56** [comment]
<img width="1435" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/90ad9d8e-3fcb-4aca-9167-16d13730999f">
<img width="1439" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/e9c50d36-c6d6-4de4-ac68-bc9555676088">

**Comment by thanhpd56** [comment]
Grid is working well. 
<img width="1439" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/8562a319-6e16-47f6-90ea-4c2982d5eb87">

**Comment by thanhpd56** [comment]
@aptkingston Sorry for bothering you, but I really need your help.

**Comment by aptkingston** [comment]
Does the internal DB work? For example the sample data?

**Comment by thanhpd56** [comment]
[error] 2023-07-25T10:19:48.732496Z couchdb@couchdb-couchdb-0.couchdb-couchdb.database.svc.cluster.local <0.4941.0> -------- ** 'couchdb@couchdb-couchdb-0.couchdb-couchdb.database.svc.cluster.local': Connection attempt to node 'clouseau@127.0.0.1' aborted since it cannot handle ["BIG_CREATION"].**
When I create new app from sample data, I got this error. I deployed Budibase to K8S cluster by helmchart. :(

**Comment by aptkingston** [comment]
Going to convert this to a discussion since it seems like an environment issue.

**Comment by thanhpd56** [comment]
https://github.com/Budibase/budibase/assets/3794898/1da6f05d-473f-4797-8f20-f504020dad78

@aptkingston I recreated Budibase with couchdb cluster size = 1 then be able to create new app from sample data successfully. However, table block still shows empty even data already existed. 
Beside that, as you can see from screen, I see that Budibase call 2 search requests to get data, first request returns rows, second request returns no data. Is that the cause of problem?

**Reply by thanhpd56** [reply]
Payload of first request: `{"query":{"string":{},"fuzzy":{},"range":{},"equal":{},"notEqual":{},"empty":{},"notEmpty":{},"contains":{},"notContains":{},"oneOf":{},"containsAny":{}},"bookmark":null,"limit":8,"sort":"First Name","sortOrder":"ascending","sortType":"string","paginate":true}`

Payload of second request: `{"query":{"string":{},"fuzzy":{},"range":{},"equal":{"_id":"{{ [state].[ID_hMmoQYkl2m] }}"},"notEqual":{},"empty":{},"notEmpty":{},"contains":{},"notContains":{},"oneOf":{},"containsAny":{}},"bookmark":null,"limit":1,"sort":"First Name","sortOrder":"ascending","sortType":"string","paginate":false}`

**Reply by thanhpd56** [reply]
I do the same thing in the cloud version of budibase then the table block is working well. However, on the self hosted version, it shows nothing. :(

**Reply by thanhpd56** [reply]
Here is the helm values. chart version 2.8.22
```
    image:
      pullPolicy: IfNotPresent
      tag: 2.8.22
    ingress:
      enabled: false
      nginx: false
    globals:
      appVersion: "2.8.22"
    ingress-nginx:
    services:
      apps:
        httpLogging: 1
        logLevel: info
        port: 4002
        replicaCount: 1
        resources: {}
      budibaseVersion: latest
      couchdb:
        enabled: true
        port: 5984
      dns: cluster.local
      objectStore:
        browser: true
        minio: true
        port: 9000
        replicaCount: 1
        storage: 1Gi
      redis:
        enabled: true
      worker:
        httpLogging: 1
        logLevel: info
        port: 4003
        replicaCount: 1
    couchdb:
      ## clusterSize is the initial size of the CouchDB cluster.
      clusterSize: 1
      allowAdminParty: false

      # Secret Management
      createAdminSecret: true


```

**Reply by aptkingston** [reply]
The first request is the one fetching data for your table, the second one is a request for editing a row in the side panel of the table block, which is not being used in that example so it is expected that it will return nothing.

The first request definitely has data? If there is data then it should be visible in your table.

**Reply by aptkingston** [reply]
I watched your recording (thanks for providing it) and yes that looks completely normal. That's exactly what your requests should look like for loading data.

**Reply by aptkingston** [reply]
Have you tried publishing your app and seeing if the same thing happens? In case it's unique to the preview.

**Reply by thanhpd56** [reply]
@aptkingston yes, I already published several times, but nothing changes.

**Reply by thanhpd56** [reply]
https://widget.intercom.io/widget/qz2sxfuv I see on my browser that, cannot download this js lib, does it related to this issue?

**Reply by aptkingston** [reply]
No that isn't related - it's totally fine if there are errors loading intercom or posthog, they're all optional.

**Reply by thanhpd56** [reply]
Hi, I guess I found where is the problem come from. Instead of using ingress of k8s (contour) with domain, I try to port-forward and access with localhost:10000 then the data is show-up. Is there any special ingress configuration that I need to aware?

**Reply by thanhpd56** [reply]
<img width="937" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/93561895-3c8d-49af-8482-adcf692d08f1">
Seem like websocket problem - pending forever.

**Reply by thanhpd56** [reply]
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app.kubernetes.io/instance: budibase
    app.kubernetes.io/version: 1.0.0
  name: budibase
  namespace: budibase
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true # Setting this to true enables websocket for all paths that match /
      services:
        - name: proxy-service
          port: 10000
      timeoutPolicy:
        response: 500m
        idle: 100m
      responseHeadersPolicy:
        set:
          - name: Content-Security-Policy
            value: "default-src 'self' 'unsafe-inline' js.intercomcdn.com widget.intercom.io s3.ap-southeast-1.amazonaws.com *.budibase.net *.budi.live js.intercomcdn.widget.intercom.io *.amazonaws.com *.posthog.com *.c-group.global; frame-ancestors 'self' http://localhost:3000"
          - name: Strict-Transport-Security
            value: max-age=31536000; includeSubDomains
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowHeaders:
        - '*'
      allowMethods:
        - '*'
      allowOrigin:
        - '*'
      maxAge: 1h
    fqdn: ***
    tls:
      secretName: ***

```
