### DISCUSSION TITLE
[BUDI-6923] Created Helm chart with PVs, pod goes down, where is data?

### DISCUSSION THREAD

**Discussion by Rambatino** [Budibase/budibase#11369] [Help]
Created the helm chart with PVs enabled:

``` tf
resource "helm_release" "budibase" {
  count = local.var.unencrypted.env == "production" ? 1 : 0

  name       = "budibase"
  chart      = "budibase"
  repository = "https://budibase.github.io/budibase/"
  namespace  = kubernetes_namespace.budibase.id

  set {
    name  = "couchdb.image.tag"
    value = "3.1.0"
  }

  set {
    name  = "couchdb.persistentVolume.enabled"
    value = true
  }
}
```

Everything working fine, had some apps running on there. Deleted `budibase-couchdb-0`, and now i can't login, no one can.

How do I recover my data?

container yaml has this:

``` yaml
Containers:
  couchdb:
    Container ID:   docker://f4fbc02005fb270008d7fe5926675e9025aefb7121d171ad0df9a33a41b5ab0e
    Image:          couchdb:3.1.0
    Image ID:       docker-pullable://couchdb@sha256:b604d056d8024f10346eab768de7aea06bc0a1b7c55d6087e1b1cd4328c8061c
    Ports:          5984/TCP, 4369/TCP, 9100/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 25 Apr 2023 10:57:54 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:5984/_up delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:5984/_up delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      COUCHDB_USER:      <set to the key 'adminUsername' in secret 'budibase-couchdb'>     Optional: false
      COUCHDB_PASSWORD:  <set to the key 'adminPassword' in secret 'budibase-couchdb'>     Optional: false
      COUCHDB_SECRET:    <set to the key 'cookieAuthSecret' in secret 'budibase-couchdb'>  Optional: false
      ERL_FLAGS:          -name couchdb  -setcookie monster
    Mounts:
      /opt/couchdb/data from database-storage (rw)
      /opt/couchdb/etc/default.d from config-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2xkdx (ro)
  clouseau:
    Container ID:   docker://6f0a384fe08a0ad66e71db9c7388c500f7642b79844edbeef3af19f4659bc2cd
    Image:          kocolosk/couchdb-search:0.2.0
    Image ID:       docker-pullable://kocolosk/couchdb-search@sha256:2051ed964a50f3896beee577f8b0068c86fa923ffaa36dcf2f3694fe38acd188
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 25 Apr 2023 10:57:54 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/couchdb-search/data from database-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2xkdx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  database-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  database-storage-budibase-couchdb-0
    ReadOnly:   false
```

<sub>[BUDI-6923](https://linear.app/budibase/issue/BUDI-6923/created-helm-chart-with-pvs-pod-goes-down-where-is-data)</sub>
