### DISCUSSION TITLE
Allow editing relationship data from parent edit row field

### DISCUSSION THREAD

**Discussion by tyteen4a03** [Budibase/budibase#11602] [Help]
I have the following table setup:

```
Item:
  name: string
  ... other fields
  item_type: ItemType

ItemTypes:
  name: string
  table_name: string
```

And for each `ItemType` row I have a new table. For example, if I have `ItemType` `grocery` and `medicine`, each `Item` can be one of `grocery` or `medicine`, and it would have further properties under `GroceryItem` or `MedicineItem`. In other words, `items` is a polymorphic / faceted row with its features in subtables. Each `Item` will only have one `type`, but we will be continually adding new types into the database.

How can I make it so that the panel that edits the parent Item can also show the panel that edits `GroceryItem` or `MedicineItem` depending on the Item's `type`?
