### DISCUSSION TITLE
Use of S3 as backend instead of Minio

### DISCUSSION THREAD

**Discussion by regi4life** [Budibase/budibase#12532] [Help]
Hi all,

I would like to migrate from Minio to Amazon S3 for the storage of objects/config.
I provided the ACCESS KEY, the ACCESS SECRET and the S3 URL by using the endpoint type s3:// or https://. The IAM user having the access key and the secret key has full permsions for S3.

It still does not work. I cannot create new app, store new objects in the S3 bucket.

Please can you tell me how the S3 URL should look like and what permissions my IAM user shoud have and if I should modify the S3 bucket ACLs.

**Comment by melohagan** [comment]
What errors do you see when you try to set this up @regi4life ?

**Reply by regi4life** [reply]
Hi @melohagan,

Thanks for your comment. When I am trying to create a new app by example I am getting the mesage "error creating app". In the logs below we can see that the app cannot write to the object store bucket.

{"level":"ERROR","timestamp":"2023-12-13T13:56:51.350Z","service":"@budibase/server","err":{"type":"Error","message":"Unable to write to object store bucket.","stack":"Error: Unable to write to object store bucket.\n    at makeSureBucketExists (/app/dist/index.js:93555:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async streamUpload (/app/dist/index.js:93592:3)\n    at async Promise.all (index 0)\n    at async uploadDirectory (/app/dist/index.js:93765:3)\n    at async Promise.all (index 0)\n    at async uploadDirectory (/app/dist/index.js:93765:3)\n    at async Promise.all (index 1)\n    at async uploadDirectory (/app/dist/index.js:93765:3)\n    at async Object.downloadTarball (/app/dist/index.js:93786:5)\n    at async getTemplateStream (/app/dist/index.js:169682:21)\n    at async Object.importApp (/app/dist/index.js:169756:16)\n    at async createInstance (/app/dist/index.js:201671:5)\n    at async /app/dist/index.js:201746:22\n    at async performAppCreate (/app/dist/index.js:201745:10)\n    at async tryIncrement (/app/dist/index.js:164711:24)\n    at async create9 (/app/dist/index.js:201864:26)\n    at async /app/node_modules/koa-compress/lib/index.js:38:5\n    at async errorHandling (/app/dist/index.js:155307:5)\n    at async /app/node_modules/koa-mount/index.js:52:26\n    at async userAgent (/app/node_modules/koa-useragent/dist/index.js:12:5)"},"pid":30,"tenantId":"default","correlationId":"c31446d3-0f27-4171-b6b5-761f811f1738","msg":""}

Regards,

**Reply by melohagan** [reply]
Hey @regi4life 

Make sure the following env variables are set:

- `MINIO_ACCESS_KEY`
- `MINIO_SECRET_KEY`
- `MINIO_URL`

**Reply by regi4life** [reply]
Even if the parameters were defined in the values.yaml like below:
```
    minio: false
    browser: true
    port: 9000
    replicaCount: 1
    accessKey: "XXXXXXXXXXXXXXXXXXXX" # AWS_ACCESS_KEY if using S3 or existing minio access key
    secretKey: "XYZZZZZZZZZZZZZZZZZZ" # AWS_SECRET_ACCESS_KEY if using S3 or existing minio secret
    region: "eu-west-1" # AWS_REGION if using S3 or existing minio secret
    url: "s3://xsxsxsxssxsxsxsx" # only change if pointing to existing minio cluster or S3 and minio: false
```

**Reply by melohagan** [reply]
Ah nevermind didn't realise you were using kubernetes

**Reply by regi4life** [reply]
My bad, I did not mention that I made my deployment on AWS EKS. As I am on AWS I don't want to use resources (cpu and memory) for an instance of minio.

**Reply by refucktor** [reply]
@regi4life since this is still unanswered, here is my contribution:

**THIS APPLIES TO DEPLOYMENTS TO K8S**, in my case using the Helm Chart

1. In order to successfully use the object storage with AWS S3 instead of the built-in option of Minio, here is the combination that works:

```yaml
services:
  objectStore:
    minio: false
    accessKey: <YOUR_ACCESS_KEY> # I recommend using a different mechanism to provide it
    secretKey: <YOUR_SECRET_KEY> # same as above, if you are interested in options let me know and I can give you some
    url: "" # THIS IS VERY IMPORTANT, checking the code I noticed that if there is any value in the url, it's kind of assuming you are using an object storage alternative like minio, just leave it blank
```

2. Now comes the bad news, if your AWS credentials are session based (meaning, they require to be used alongside an `AWS_SESSION_TOKEN`) you are basically screwed. I'm preparing a PR to fix that part
