### DISCUSSION TITLE
[BUDI-7828] Error with k8s helm upgrade of budibase to 2.9.x

### DISCUSSION THREAD

**Discussion by megatron757** [Budibase/budibase#12651] [Help]
**Checklist**

* \[x \] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: k8s
  * Budibase Version: 2.9.2 and 2.9.5 (2.8.30 deploys correctly)
  * App Version: 2.9.2 and 2.9.5

**Describe the bug**
I am receiving an error when I attempt to upgrade the helm release from 2.8.30 to 2.9.2 or 2.9.5.

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe
```

**To Reproduce**

1. Issue commands:
2. `helm repo update`
3. `helm upgrade budibase budibase/budibase -f values.yaml -n budibase --atomic`
4. The error also persists on a fresh install of the helm chart in a new namespace (without changing anything in values.yaml) `helm install --namespace budibase budibase budibase/budibase`

**Expected behavior**
I expect the upgrade to happen without error

**Screenshots**
I tried commenting out the enabled parameter in values.yaml, but that did not make a difference:

![Screenshot 2023-08-11 at 11 02 03 AM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/08202ee1-6ac0-4b82-8f6d-96d0650919c6/326a92c6-4ea7-4961-a320-1967f525f804?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8wODIwMmVlMS02YWMwLTRiODItOGY2ZC05NmQwNjUwOTE5YzYvMzI2YTkyYzYtNGVhNy00OTYxLWEzMjAtMTk2N2Y1MjVmODA0IiwiaWF0IjoxNzAyMzA1MjcwLCJleHAiOjE3MDIzOTE2NzB9.KflwwT_6Dn4EObTR_2FIMho2ugHYA1yjmlHEbJYBHd0)

**Additional context**
I made 2 other modifications to the values.yaml file. The rest are default.

![Screenshot 2023-08-11 at 11 04 41 AM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ed8756cb-66a1-4f8d-92af-f61681556893/929d625e-b878-460b-9b01-56e88266dbcc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lZDg3NTZjYi02NmExLTRmOGQtOTJhZi1mNjE2ODE1NTY4OTMvOTI5ZDYyNWUtYjg3OC00NjBiLTliMDEtNTZlODgyNjZkYmNjIiwiaWF0IjoxNzAyMzA1MjcwLCJleHAiOjE3MDIzOTE2NzB9.igpngtp-so28sqq-xazcrCiz8ZoDetPC_wzgilLRxPM)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7828](https://linear.app/budibase/issue/BUDI-7828/error-with-k8s-helm-upgrade-of-budibase-to-29x)</sub>

**Comment by nlahmi** [comment]
Having the same issue with a fresh install

**Comment by jonnymccullagh** [comment]
We have recently made a change to these parameters to move the blocks into the values file that we have not been able to fully test for operational reasons. Can I check the content of your `values.yaml` file, that your values are under:
```
.Values.services.worker.startupProbe
.Values.services.worker.livenessProbe
.Values.services.worker.readinessProbe
```
And similar for `apps`.
In the meantime you should still be able to deploy by commenting out those values in your values.yaml until we can get more testing done.

**Comment by megatron757** [comment]
> We have recently made a change to these parameters to move the blocks into the values file that we have not been able to fully test for operational reasons. Can I check the content of your `values.yaml` file, that your values are under:
> 
> ```
> .Values.services.worker.startupProbe
> .Values.services.worker.livenessProbe
> .Values.services.worker.readinessProbe
> ```
> 
> And similar for `apps`. In the meantime you should still be able to deploy by commenting out those values in your values.yaml until we can get more testing done.

Hi,

Tried again with a fresh install: 
`helm install --namespace budibase budibase budibase/budibase -f fresh-values.yaml`

Error: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe`

fresh-values.yaml (copied directly from helm chart install - commented out `enabled: true` on `services.worker.readinessProbe` and `services.app.readinessProbe`)
```
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
couchdb:
  adminUsername: admin
  affinity: {}
  allowAdminParty: false
  annotations: {}
  clusterSize: 1
  couchdbConfig:
    chttpd:
      bind_address: any
      require_valid_user: false
    couchdb:
      uuid: budibase-couchdb
  createAdminSecret: true
  dns:
    clusterDomainSuffix: cluster.local
  enableSearch: true
  erlangFlags:
    name: couchdb
    setcookie: monster
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: couchdb
    tag: 3.1.1
  ingress:
    annotations: []
    enabled: false
    hosts:
    - chart-example.local
    path: /
    tls: null
  initImage:
    pullPolicy: Always
    repository: busybox
    tag: latest
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  networkPolicy:
    enabled: true
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: false
    size: 10Gi
    storageClass: ""
  podManagementPolicy: Parallel
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources: {}
  searchImage:
    pullPolicy: IfNotPresent
    repository: kocolosk/couchdb-search
    tag: 0.2.0
  service:
    enabled: true
    externalPort: 5984
    type: ClusterIP
  serviceAccount:
    create: true
    enabled: true
  sidecars: {}
  tolerations: []
globals:
  accountPortalApiKey: ""
  accountPortalUrl: ""
  apiEncryptionKey: ""
  appVersion: ""
  automationMaxIterations: "200"
  budibaseEnv: PRODUCTION
  cdnUrl: ""
  cookieDomain: ""
  createSecrets: true
  enableAnalytics: "1"
  google:
    clientId: ""
    secret: ""
  httpMigrations: "0"
  internalApiKey: ""
  internalApiKeyFallback: ""
  jwtSecret: ""
  jwtSecretFallback: ""
  multiTenancy: "0"
  offlineMode: "0"
  platformUrl: ""
  posthogToken: phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU
  selfHosted: "1"
  sentryDSN: ""
  smtp:
    enabled: false
  tenantFeatureFlags: '*:LICENSING,*:USER_GROUPS,*:ONBOARDING_TOUR'
image:
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 150M
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  aws: false
  certificateArn: ""
  className: ""
  enabled: true
  hosts:
  - host: null
    paths:
    - backend:
        service:
          name: proxy-service
          port:
            number: 10000
      path: /
      pathType: Prefix
  nginx: true
ingress-nginx:
  controller:
    addHeaders: {}
    admissionWebhooks:
      annotations: {}
      certificate: /usr/local/certificates/cert
      createSecretJob:
        resources: {}
      enabled: true
      existingPsp: ""
      failurePolicy: Fail
      key: /usr/local/certificates/key
      labels: {}
      namespaceSelector: {}
      objectSelector: {}
      patch:
        enabled: true
        image:
          digest: sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
          image: ingress-nginx/kube-webhook-certgen
          pullPolicy: IfNotPresent
          registry: k8s.gcr.io
          tag: v1.1.1
        labels: {}
        nodeSelector:
          kubernetes.io/os: linux
        podAnnotations: {}
        priorityClassName: ""
        runAsUser: 2000
        tolerations: []
      patchWebhookJob:
        resources: {}
      port: 8443
      service:
        annotations: {}
        externalIPs: []
        loadBalancerSourceRanges: []
        servicePort: 443
        type: ClusterIP
    affinity: {}
    allowSnippetAnnotations: true
    annotations: {}
    autoscaling:
      behavior: {}
      enabled: false
      maxReplicas: 11
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    autoscalingTemplate: []
    config: {}
    configAnnotations: {}
    configMapNamespace: ""
    containerName: controller
    containerPort:
      http: 80
      https: 443
    customTemplate:
      configMapKey: ""
      configMapName: ""
    dnsConfig: {}
    dnsPolicy: ClusterFirst
    electionID: ingress-controller-leader
    enableMimalloc: true
    existingPsp: ""
    extraArgs: {}
    extraContainers: []
    extraEnvs: []
    extraInitContainers: []
    extraVolumeMounts: []
    extraVolumes: []
    healthCheckHost: ""
    healthCheckPath: /healthz
    hostNetwork: false
    hostPort:
      enabled: false
      ports:
        http: 80
        https: 443
    hostname: {}
    image:
      allowPrivilegeEscalation: true
      digest: sha256:f766669fdcf3dc26347ed273a55e754b427eb4411ee075a53f30718b4499076a
      image: ingress-nginx/controller
      pullPolicy: IfNotPresent
      registry: k8s.gcr.io
      runAsUser: 101
      tag: v1.1.0
    ingressClassByName: false
    ingressClassResource:
      controllerValue: k8s.io/ingress-nginx
      default: false
      enabled: true
      name: nginx
      parameters: {}
    keda:
      apiVersion: keda.sh/v1alpha1
      behavior: {}
      cooldownPeriod: 300
      enabled: false
      maxReplicas: 11
      minReplicas: 1
      pollingInterval: 30
      restoreToOriginalReplicaCount: false
      scaledObject:
        annotations: {}
      triggers: []
    kind: Deployment
    labels: {}
    lifecycle:
      preStop:
        exec:
          command:
          - /wait-shutdown
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    maxmindLicenseKey: ""
    metrics:
      enabled: false
      port: 10254
      prometheusRule:
        additionalLabels: {}
        enabled: false
        rules: []
      service:
        annotations: {}
        externalIPs: []
        loadBalancerSourceRanges: []
        servicePort: 10254
        type: ClusterIP
      serviceMonitor:
        additionalLabels: {}
        enabled: false
        metricRelabelings: []
        namespace: ""
        namespaceSelector: {}
        relabelings: []
        scrapeInterval: 30s
        targetLabels: []
    minAvailable: 1
    minReadySeconds: 0
    name: controller
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: ""
    proxySetHeaders: {}
    publishService:
      enabled: true
      pathOverride: ""
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    replicaCount: 1
    reportNodeInternalIp: false
    resources:
      requests:
        cpu: 100m
        memory: 90Mi
    scope:
      enabled: false
      namespace: ""
      namespaceSelector: ""
    service:
      annotations: {}
      appProtocol: true
      enableHttp: true
      enableHttps: true
      enabled: true
      external:
        enabled: true
      externalIPs: []
      internal:
        annotations: {}
        enabled: false
        loadBalancerSourceRanges: []
      ipFamilies:
      - IPv4
      ipFamilyPolicy: SingleStack
      labels: {}
      loadBalancerSourceRanges: []
      nodePorts:
        http: ""
        https: ""
        tcp: {}
        udp: {}
      ports:
        http: 80
        https: 443
      targetPorts:
        http: http
        https: https
      type: LoadBalancer
    sysctls: {}
    tcp:
      annotations: {}
      configMapNamespace: ""
    terminationGracePeriodSeconds: 300
    tolerations: []
    topologySpreadConstraints: []
    udp:
      annotations: {}
      configMapNamespace: ""
    updateStrategy: {}
    watchIngressWithoutClass: false
  defaultBackend:
    affinity: {}
    autoscaling:
      annotations: {}
      enabled: false
      maxReplicas: 2
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    containerSecurityContext: {}
    enabled: false
    existingPsp: ""
    extraArgs: {}
    extraEnvs: []
    extraVolumeMounts: []
    extraVolumes: []
    image:
      allowPrivilegeEscalation: false
      image: defaultbackend-amd64
      pullPolicy: IfNotPresent
      readOnlyRootFilesystem: true
      registry: k8s.gcr.io
      runAsNonRoot: true
      runAsUser: 65534
      tag: "1.5"
    labels: {}
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    minAvailable: 1
    name: defaultbackend
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    port: 8080
    priorityClassName: ""
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    replicaCount: 1
    resources: {}
    service:
      annotations: {}
      externalIPs: []
      loadBalancerSourceRanges: []
      servicePort: 80
      type: ClusterIP
    serviceAccount:
      automountServiceAccountToken: true
      create: true
      name: ""
    tolerations: []
  global: {}
  imagePullSecrets: []
  podSecurityPolicy:
    enabled: false
  rbac:
    create: true
    scope: false
  revisionHistoryLimit: 10
  serviceAccount:
    automountServiceAccountToken: true
    create: true
    name: ""
  tcp: {}
  udp: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  port: 10000
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
services:
  apps:
    httpLogging: 1
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 4002
        scheme: HTTP
      periodSeconds: 5
    logLevel: info
    port: 4002
    readinessProbe:
      #enabled: true
      failureThreshold: 1
      httpGet:
        path: /health
        port: 4002
        scheme: HTTP
      periodSeconds: 3
    replicaCount: 1
    resources: {}
    startupProbe:
      failureThreshold: 30
      httpGet:
        path: /health
        port: 4002
        scheme: HTTP
      periodSeconds: 3
  budibaseVersion: latest
  couchdb:
    backup:
      enabled: false
      interval: ""
      resources: {}
      target: ""
    enabled: true
    port: 5984
  dns: cluster.local
  objectStore:
    accessKey: ""
    browser: true
    cloudfront:
      cdn: ""
      privateKey64: ""
      publicKeyId: ""
    minio: true
    port: 9000
    region: ""
    replicaCount: 1
    resources: {}
    secretKey: ""
    storage: 100Mi
    storageClass: ""
    url: http://minio-service:9000
  proxy:
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 10000
        scheme: HTTP
      periodSeconds: 5
    port: 10000
    readinessProbe:
      enabled: true
      failureThreshold: 1
      httpGet:
        path: /health
        port: 10000
        scheme: HTTP
      periodSeconds: 3
    replicaCount: 1
    resources: {}
    startupProbe:
      failureThreshold: 30
      httpGet:
        path: /health
        port: 10000
        scheme: HTTP
      periodSeconds: 3
    upstreams:
      apps: http://app-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns
        }}:{{ .Values.services.apps.port }}
      couchdb: http://{{ .Release.Name }}-svc-couchdb:{{ .Values.services.couchdb.port
        }}
      minio: http://minio-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns
        }}:{{ .Values.services.objectStore.port }}
      worker: http://worker-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns
        }}:{{ .Values.services.worker.port }}
  redis:
    enabled: true
    password: budibase
    port: 6379
    replicaCount: 1
    resources: {}
    storage: 100Mi
    storageClass: ""
    url: ""
  worker:
    httpLogging: 1
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 4003
        scheme: HTTP
      periodSeconds: 5
    logLevel: info
    port: 4003
    readinessProbe:
      #enabled: true
      failureThreshold: 1
      httpGet:
        path: /health
        port: 4003
        scheme: HTTP
      periodSeconds: 3
    replicaCount: 1
    resources: {}
    startupProbe:
      failureThreshold: 30
      httpGet:
        path: /health
        port: 4003
        scheme: HTTP
      periodSeconds: 3
tolerations: []

```

**Comment by jonnymccullagh** [comment]
Hi @megatron757, the problem is we had some erroneous lines for `enabled: true` in the example `values.yaml` for probes. I have a PR to fix that but in the meantime you could also try removing those lines from your `values.yaml`. From your code above specifically lines 43, 
59 and 504 still have `enabled: true` for probes.

**Comment by megatron757** [comment]
Hi @jonnymccullagh I commented out all the `enabled: true` lines but am still receiving the error. (used values.yaml - attached here as values.txt)
[values.txt](https://github.com/Budibase/budibase/files/12371136/values.txt)

I looked up the [commit](https://github.com/Budibase/budibase/pull/11528/commits/e5046c1bca10e86c78192820eeb0cad9055ea519) on the PR you referenced and tried using your updated values.yaml file but the same error persists. (used values-PR.yaml attached here as values-PR.txt)
[values-PR.txt](https://github.com/Budibase/budibase/files/12371147/values-PR.txt)

**Comment by megatron757** [comment]
Hi, wanted to leave a quick update that I tried using the new version that looks to include the PR that removes the enabled: true parameters from values.yaml. 

I ran `helm repo update` then attempted deploying the helm chart (a fresh install, not an upgrade) with all default values on version 2.9.25, but unfortunately I received the same error.

**Comment by megatron757** [comment]
@jonnymccullagh I wanted to provide another update: The issue with the readinessProbe appears to be resolved in 2.9.30 - thank you! But I ran into another issue when upgrading. 

It appears that the template is attempting to create new secrets instead of using the existing secrets from the initial install. 

Error in app-service pod:
```
{"level":"ERROR","timestamp":"2023-08-21T18:49:35.649Z","service":"@budibase/server","err":{"type":"Error","message":"Name or password is incorrect.","stack":"Error: Name or password is incorrect.\n    at responseHandler (/app/dist/index.js:21325:24)\n    at /app/dist/index.js:21515:17\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","scope":"couch","statusCode":401,"request":{"method":"put","headers":{"content-type":"application/json","accept":"application/json","user-agent":"@budibase/nano/10.1.2 (Node.js v14.21.3)","Accept-Encoding":"deflate, gzip","Authorization":"Basic SECRET"},"qsStringifyOptions":{"arrayFormat":"repeat"},"url":"http://budibase-hrdb-svc-couchdb:5984/global-db","paramsSerializer":{},"maxRedirects":0,"httpAgent":{"_events":{},"_eventsCount":2,"defaultPort":80,"protocol":"http:","options":{"jar":{"version":"tough-cookie@4.1.2","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"enableLooseMode":false,"allowSpecialUseDomain":true,"prefixSecurity":"silent","cookies":[]},"keepAlive":true,"maxSockets":50,"keepAliveMsecs":30000,"path":null},"requests":{},"sockets":{},"freeSockets":{"budibase-hrdb-svc-couchdb:5984:":[{"connecting":false,"_hadError":false,"_parent":null,"_host":"budibase-hrdb-svc-couchdb","_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":true,"decoder":null,"encoding":null},"_events":{},"_eventsCount":6,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"closeEmitted":false,"writable":true},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null,"parser":null,"_httpMessage":null,"timeout":0}]},"keepAliveMsecs":30000,"keepAlive":true,"maxSockets":50,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0,"jar":{"version":"tough-cookie@4.1.2","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"enableLooseMode":false,"allowSpecialUseDomain":true,"prefixSecurity":"silent","cookies":[]}},"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"jar":{"version":"tough-cookie@4.1.2","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"enableLooseMode":false,"allowSpecialUseDomain":true,"prefixSecurity":"silent","cookies":[]},"keepAlive":true,"maxSockets":50,"keepAliveMsecs":30000,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":30000,"keepAlive":true,"maxSockets":50,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]},"jar":{"version":"tough-cookie@4.1.2","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"enableLooseMode":false,"allowSpecialUseDomain":true,"prefixSecurity":"silent","cookies":[]}}},"headers":{"uri":"http://budibase-hrdb-svc-couchdb:5984/global-db","statusCode":401,"cache-control":"must-revalidate","content-type":"application/json","date":"Mon, 21 Aug 2023 18:49:34 GMT","x-couch-request-id":"5a849eba77","x-couchdb-body-time":"0"},"errid":"non_200","name":"Error","description":"Name or password is incorrect.","error":"unauthorized","reason":"Name or password is incorrect."},"pid":30,"tenantId":"default","msg":""}
```

Attempted to specify the secret in values.yaml: 
```
helm upgrade budibase-hrdb budibase/budibase -f values.yaml -n web3tech-hrdb --atomic
Error: UPGRADE FAILED: template: budibase/charts/couchdb/templates/_helpers.tpl:40:8: executing "couchdb.defaultsecret" at <b64enc>: wrong type for value; expected string; got map[string]interface {}
```
values.yaml file:
```
couchdb:
  adminUsername: admin
  adminPassword:
    secretName: budibase-hrdb-couchdb
    secretKey: adminPassword
```

#### 
Next, for testing, I explicitly specified the `adminPassword` in `values.yaml` and the upgrade appeared to succeed, but the App would not load due to this error: 
"There was an error loading your app. The Budibase client library could not be loaded. Try republishing your app."

Error in app-service pod:
```
{"level":"ERROR","timestamp":"2023-08-21T19:11:00.709Z","service":"@budibase/server","err":{"type":"Error","message":"The Access Key Id you provided does not exist in our records.","stack":"InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:699:35)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/app/node_modules/aws-sdk/lib/event_listeners.js:335:13)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)","code":"InvalidAccessKeyId","region":null,"time":"2023-08-21T19:11:00.709Z","requestId":"177D7BB6F64C47E0","extendedRequestId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","statusCode":403,"retryable":false,"retryDelay":19.300793881660596},"pid":30,"tenantId":"default","appId":"app_dev_db04b787eade495ca6d3a153b4172723","identityId":"us_75d6a323524647d2b2e6be265855b7b9","identityType":"user","correlationId":"72a7e10f-62e1-4e4b-8da1-b496e2d16c50","msg":"component-manifest-objectstore=failed appId=app_dev_db04b787eade495ca6d3a153b4172723 path=app_dev_db04b787eade495ca6d3a153b4172723/manifest.json"}
```

I encountered this error previously when upgrading the helm chart, but did not document specifics at that time. 

Maybe the template needs to be updated to check for existence of secrets before recreating? 
https://stackoverflow.com/questions/67617808/helm-how-to-avoid-recreating-secrets-on-upgrade

Thanks for your help!
