### DISCUSSION TITLE
[K8S] Does Budibase support connecting to an external Redis cluster/Redis sentinel running on the same k8s cluster ?

### DISCUSSION THREAD

**Discussion by Antoine1212** [Budibase/budibase#12941] [Help]
I'm trying to set up a HA Budibase deployment and as such i need an external Redis database. I've deployed a Redis cluster but i can't manage to connect my budibase instances to it, so i've also tried setting up a connection between Budibase and Redis sentinel, but no luck there either.
I've been setting up this configuration in my `values.yaml` file for my Budibase deployment:

```
services:
  redis:
    enabled: false
    #this is the url i used when trying to connect to the Redis cluster
    url: "redis://redis.redis.svc.cluster.local:6379"
    #this is the url i used when trying to connect to the Redis sentinel
    url: "redis-sentinel://redis.redis.svc.cluster.local:26379/0?sentinelMasterId=mymaster"
    password: "mypassword"
    storageClass: ""
    resources: {}
```
The only time i've been able to make it work was using a default external Redis deployment.
Does Budibase support connecting to a Redis sentinel DB or a Redis cluster DB ? If not, are there any plans for it ?
I'd appreciate any help, thanks !
