### DISCUSSION TITLE
Need Help Resolving 504 Error in  /api/templates Docker Setup on Localhost

### DISCUSSION THREAD

**Discussion by hunsche** [Budibase/budibase#14277] [Help] [answered]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.29.25

**Describe the bug**
After setting up Budibase via Docker Compose and creating a root user, the initial login works. However, the first screen takes a long time to load and eventually stalls on a request to http://localhost:8080/api/templates, which returns a 504 Gateway Timeout error. This prevents any further interaction with the application on localhost.

**To Reproduce**
1. Set up Budibase using Docker Compose as per the official [documentation](https://docs.budibase.com/docs/docker).
```yaml
version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:2.29.25
    ports:
      - "8080:80"
    volumes:
      - budibase_data:/data

volumes:
  budibase_data:
    driver: local
```
2. Access Budibase on http://localhost:8080 and create a root user.
3. Log in with the newly created root user.
4. Attempt to access the main dashboard at http://localhost:8080/builder/portal/apps.
5. Observe that the application loads indefinitely and finally fails with a 504 error in GET http://localhost:8080/api/templates.

**Expected behavior**
Expected the application to load successfully without any delays or gateway errors, allowing for normal usage and exploration of Budibase features locally.

**Screenshots**
Attached is a screenshot showing the stalled loading screen and network errors.
![Screenshot from 2024-07-30 10-21-08](https://github.com/user-attachments/assets/a07a2559-e267-4207-9b7e-2845a5592078)

**Desktop (please complete the following information):**
 - OS: Linux pop-os 6.9.3-76060903-generic
 - Browser chrome
 - Version 127.0.6533.72 (Official Build) (64-bit)

**Additional context**
I have tried multiple versions of the Budibase Docker image and different browsers, but all exhibit the same issue. I'm looking for any guidance on how to resolve this or alternative setup configurations that might bypass this problem.
