### DISCUSSION TITLE
Stat cards custom font colors

### DISCUSSION THREAD

**Discussion by aowdnmp** [Budibase/budibase#14656] [Help]
Hello, i'm new to budibase and now experimenting. I've created some stat cards that by default have the value shown in blue.
I thought with custom css I was able to oveeride font color for some values that needs to be highlighted in red, for example.
Inspecting the code I found the right names but I'm not able to replace the color with a custom one. Someone knows the correct way to do this? Thanks

.value.svelte-13s6ero {
    font-size: 2rem;
    font-weight: 600;
    margin: 0 1.5rem 1.5rem 1.5rem;
    color: var(--spectrum-link-primary-m-text-color);
    white-space: pre-wrap;
}

**Comment by ConorWebb96** [comment]
Hey @aowdnmp,

For this, you'll likely have to use the embed component above your stat card in your component tree. I've attached a screenshot below of this.

<img width="1177" alt="Screenshot 2024-09-30 at 08 29 12" src="https://github.com/user-attachments/assets/21c31794-c774-4a1a-b911-d7415ecf691d">

The code used inside the embed component looks like the one below.
```css
<style>
.value{
  font-size: 5rem!important;
  font-weight: 600;
  margin: 0 1.5rem 1.5rem 1.5rem;
  color: var(--spectrum-link-primary-m-text-color);
  white-space: pre-wrap;
}
</style>
```

Make sure to add `!important` at the end; this will ensure that it overrides the base stylings. 

I hope this helps.

**Reply by aowdnmp** [reply]
Thanks for the swift reply: if I add this everything seems changing, is the a way to change only a single card value inside a page where there are tables and other cards? I put a screen to better explain myself, circled one should be in red:

![image](https://github.com/user-attachments/assets/358e9385-fb40-4fa4-a59a-c5258836c9af)

**Reply by ConorWebb96** [reply]
Hey @aowdnmp,

I wasn't sure what your structure was, but I've created an example using `nth:` (child CSS properties).

I am using a repeater for my example. Below is the code; I renamed the repeater to `testing test` that's how I'm targeting that component specifically.

```css
<style>
.component[data-name="testing test"] .flex-container .component:first-child h3.value {
  background-color: black!important;
}
</style>
```

<img width="1206" alt="Screenshot 2024-09-30 at 11 40 52" src="https://github.com/user-attachments/assets/e617a334-d9f5-4f84-976b-6ea6df781937">
