### DISCUSSION TITLE
PostgreSQL Connection JSON Parse Error on Character 1 Line 1

### DISCUSSION THREAD

**Discussion by tobehn** [Budibase/budibase#2681] [Help]
Hey,

i made it to set up a postgresql + pgadmin via docker. I set the connection up in Buddibase (running on the same host).
In my opinion the connection between BB and PostgreSQL is "online". When i press `Fetch tables from database` i get this error: 

**Error updating datasource schema: SyntaxError: JSON.parse:unexpected character at line 1 column of the JSON data**

As i am pretty new to postgresql i am not sure if this is BB issue or if i created something wrong i the prostgreSQL DB.

Can you tell?

**Comment by mjashanks** [comment]
Hey @tobehn. That error would suggest that the connection is working ok as there is no timeout, or connection refused.

I have tried a few things, but am unable to recreate your issue. I tried
- Creating a database with no tables
- Creating a table with no rows
- Using incorrect host (different error)
- Using incorrect port (different error)

Do you have any weird characters in your table names / database?

You could try writing a custom query (at the bottom of that screen) to see if you can get that to work.

**Reply by tobehn** [reply]
@mjashanks thank you for your quick response. 

- at first i had no tables in the db
- the first db name i was triying to fetch data from had an underscore (test_db)
- tabele names are _products_ and _assemblies_
- meanwhile i tried it with a totally new db (named bmc)

Still i get the error.

A custom querry 
`SELECT * FROM public.products
ORDER BY id ASC LIMIT 100`

leads to the same error but saying:
**Query Error: JSON.parse:unexpected character at line 1 column of the JSON data**

Is ther any other log i can check? Might this refer to a Charset collisions? (DB has UTF 8)

The set up is as follows:

- Ubuntu 20.04
- docker
- bb served with caddyfile reversed to bb.mydomain.com:10000
- pgadmin and postgresql is also running as containers.
- pgadmin is also reversed with pgadmin.mydomain.com:5050
- postgresdb is localhost and is reachable via IP and Standardport

**Reply by mjashanks** [reply]
> postgresdb is localhost and is reachable via IP and Standardport

So - in budibase what is your `host` set to, for the posgres connection? If running on the same host machine as Budibase, then it should be `172.17.0.1`. This is the IP of the host, as seen from Budibase (inside a docker container).

**Reply by tobehn** [reply]
When setting the IP to 172.17.0.1 i get the same error. 

Connection should be fine. Though i do not know what kind of JSON Read process happens in the background.

**Reply by mjashanks** [reply]
Yea, its strange, because there is nothing I can do to make that error happen.

**Reply by tobehn** [reply]
i basically have a bare ubuntu machine.
installed docker and docker-compose

in /opt/ i have your `docker-compose.yaml`, `hosting.properties` and `envoy.yaml`

Later on i created a directory `/opt/databases` with another docker-compose.yml inside.
containing the db setup:

```
version: '3.3'

services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test1234
    volumes:
      - ./mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=test
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test1234
```
of course i changed the pw an names. But basically this is it.

I cd into /opt/databses/ 
do the `docker-compose up -d`

Do these two compose files collide with each other?
