### DISCUSSION TITLE
Start Budibase Error - Envoy.yaml Read Error

### DISCUSSION THREAD

**Discussion by cfsdes** [Budibase/budibase#3323] [Help] [answered]
Anyone could help me with this issue when I try to start the budibase?

PS: I already try to set the permissions from envoy.yaml file to 777 but didn't work

<img width="1260" alt="Captura de Tela 2021-11-10 às 19 11 37" src="https://user-images.githubusercontent.com/20214824/141202280-e5d55957-2b0a-459c-b234-51da6c8e8d8c.png">

**Comment by mjashanks** [comment]
Hi There. What method are you using to run Budibase - is it this one: https://docs.budibase.com/self-hosting/hosting-methods/docker-compose ?

It seems odd that your `envoy.yaml` is inside `/etc/envoy/` - normally we would make a directory especially for the 3 budibase files, and run docker-compose from there.

**Reply by cfsdes** [reply]
I tried to run budibase both with CLI and via Docker-compose, but both didn't work. I'm using MacOS.

I made exactly the requested settings. All files (.env, docker-compose, envoy.yaml) were in the same directory.

This /etc/envoy error is apparently occurring from this mount, but I don't know how to solve it:

![Captura de Tela 2021-11-11 às 09 50 53](https://user-images.githubusercontent.com/20214824/141301111-2632e1f8-e7a4-4047-9df0-dce37535e17f.png)



Could you try the same basic procedure on your machine to run budbase to see if it works (with all dockers updated)?

**Reply by shogunpurple** [reply]
Hi @cfsdes - could you please show the output of a `ls` in the directory you are running budibase in, as well as the exact command you are using to run `docker-compose`, thanks.

**Reply by cfsdes** [reply]
Here is:

<img width="659" alt="Captura de Tela 2021-11-11 às 11 06 48" src="https://user-images.githubusercontent.com/20214824/141311836-999b6bcb-1c5b-4db3-8a8b-0ffffcdade01.png">

The command that I'm using is ``docker-compose --env-file hosting.properties up``

All these files are updated and I downloaded from [hosting](https://github.com/Budibase/budibase/tree/develop/hosting) directory from budibase project

**Reply by shogunpurple** [reply]
Ok that all looks fine. Just for sanity - can you `cat` `envoy.yaml`? It also looks like those files are owned by `root`, which could be an issue. Please try:

`sudo chown cfsdes envoy.yaml ` as well.

**Reply by cfsdes** [reply]
I changed the permissions with `chown` but still not working.


Envoy.yaml file:

```yaml
static_resources:
  listeners:
  - name: main_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_services
              domains: ["*"]
              routes:
              - match: { prefix: "/app/" }
                route:
                  cluster: app-service
                  prefix_rewrite: "/"

              - match: { path: "/v1/update" }
                route:
                  cluster: watchtower-service

              - match: { prefix: "/builder/" }
                route:
                  cluster: app-service

              - match: { prefix: "/builder" }
                route:
                  cluster: app-service
              
              - match: { prefix: "/app_" }
                route:
                  cluster: app-service

              # special cases for worker admin (deprecated), global and system API
              - match: { prefix: "/api/global/" }
                route:
                  cluster: worker-service

              - match: { prefix: "/api/admin/" }
                route:
                  cluster: worker-service

              - match: { prefix: "/api/system/" }
                route:
                  cluster: worker-service

              - match: { path: "/" }
                route:
                  cluster: app-service

              # special case for when API requests are made, can just forward, not to minio    
              - match: { prefix: "/api/" }
                route:
                  cluster: app-service
                  timeout: 120s

              - match: { prefix: "/worker/" }
                route: 
                  cluster: worker-service
                  prefix_rewrite: "/"

              - match: { prefix: "/db/" }
                route:
                  cluster: couchdb-service
                  prefix_rewrite: "/"

              # minio is on the default route because this works
              # best, minio + AWS SDK doesn't handle path proxy
              - match: { prefix: "/" }
                route:
                  cluster: minio-service

          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: app-service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: app-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: 
                address: app-service
                port_value: 4002

  - name: minio-service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: minio-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: minio-service
                port_value: 9000

  - name: worker-service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: worker-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: 
                address: worker-service
                port_value: 4003

  - name: couchdb-service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: couchdb-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: couchdb-service
                port_value: 5984

  - name: watchtower-service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: watchtower-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: 
                address: watchtower-service
                port_value: 8080


```

**Reply by boyte** [reply]
I'm having this issue as well - identical problem when trying to deploy using docker-compose on macOS Catalina.

**Reply by shogunpurple** [reply]
So I've just run this entirely from scratch on my Catalina machine and I am unable to recreate - both with `docker-compose` and the budibase CLI.

Could you provide the following information:
- Your docker version
- Your docker compose version 
- If using the CLI, how you installed - did you use the CLI from NPM, or the downloadable binary?
- Your macOS version

As a workaround, I've just pushed an image to dockerhub with `envoy.yaml` already included inside it. If you update your `docker-compose.yaml` to reflect the following, and you should be able to bypass the `envoy.yaml` bind mount altogether.

```
  proxy-service:
    restart: always
    image: budibase/envoy
    ports:
      - "${MAIN_PORT}:10000"
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

```
