### DISCUSSION TITLE
would like to have alternative config for traefik on the self host version

### DISCUSSION THREAD

**Discussion by lcslouis** [Budibase/budibase#3515] [Ideas]
Hello 
I would like to see if a alternate self host compose file be made avalible so that traefik can be used when it is installed already.

main reason is that several people may have built a swarm node using traefik reverse proxy with let's encrypt certificates so it becomes way eaiser to manage from a selfhost developer/ Server administrator

**Comment by shogunpurple** [comment]
Hi @lcslouis - so you already have a traefik proxy sitting in front of budibase. Is it not possible to just set a `loadBalancer` rule in traefik to point to budibase? I'm not that well versed in traefik, but from using it before I was able to do something like this in my traefik config to point to another server.

```
http:
  routers:
    budibase:
      rule: "Host(`yourbudibasedomain.com`)"
      service: budibase
  services:
    budibase:
      loadBalancer:
        servers:
          - url: "http://localhost:10000"

```
