### DISCUSSION TITLE
SQL query worker call timed out

### DISCUSSION THREAD

**Discussion by kovrom** [Budibase/budibase#3891] [Help] [answered]
Is it possible to adjust timeout for bigger more time consuming queries? Ran into this issue with Postgres query with few inner joins. Thank you.

**Comment by shogunpurple** [comment, marked as answer]
Hi @kovrom - are you running in our cloud or self hosted?

**Reply by kovrom** [reply]
Hi @shogunpurple, sorry forgot to mention that. Self-hosted, deployed via DigitalOcean integration. Current version
1.0.26. Thank you.

**Reply by shogunpurple** [reply]
Thanks @kovrom - so we have a hardcoded timeout set to 10 seconds on the threads that run the query. I will add an environment variable to allow this to be configurable for self hosters and it will be available in the next release.

`QUERY_THREAD_TIMEOUT: 10000` for example.

Thanks!

**Reply by kovrom** [reply]
Thank you  @shogunpurple. You guys are amazing! :) Big ups!

**Reply by charlesdsmith** [reply]
@shogunpurple Hey is that just the regular system environment variable I can set or is that a docker env variable?

**Reply by shogunpurple** [reply]
@charlesdsmith it's a docker env var:

```
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      QUERY_THREAD_TIMEOUT: 10000
```
