### DISCUSSION TITLE
Can't SSH from Digital Ocean Droplet?

### DISCUSSION THREAD

**Discussion by jeevisonline** [Budibase/budibase#4103] [Help] [answered]
I am trying to set up an application server that sends SSH commands to servers when rows get updated.

When I try to set it up in Automation, I get a response that SSH is not found.  Is this because I used a one-click DO droplet?  Or is it because it's in containers?  Or is it because that does not exist in the bash scripting on Budi

**Comment by mike12345567** [comment, marked as answer]
Hi @jeevisonline - this is a bit of a difficult one, as the bash script gets ran inside the `budibase/apps` docker container - rather than directly on the Do droplet.

Our digital ocean setup currently runs docker compose on the droplet to setup all the services we need, to run an SSH script you'll likely need to adjust the startup script for the apps container to install SSH  as we use minimal images were possible.

You can see the docker compose script used to setup the containers here: https://github.com/Budibase/budibase/blob/develop/hosting/docker-compose.yaml

If you SSH into your DO droplet you'll see this being used.

**Reply by shogunpurple** [reply]
Hey @jeevisonline - if you are running self hosted, a workaround may be to install openSSH as part of the entrypoint command on the docker container that runs budibase. You can override the server entrypoint in your `docker-compose.yaml`, so something like this may work for you and allow you to use SSH commands in automations.

```

services:
  app-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    command: apk add --no-cache openssh && yarn run:docker 
    ports:
      - "${APP_PORT}:4002"
.....
```

Then you can run `docker-compose --env-file hosting.properties up -d` to refresh your configuration.
