### DISCUSSION TITLE
budibase connection with mongodb

### DISCUSSION THREAD

**Discussion by mituBarua** [Budibase/budibase#4265] [Help]
Can anyone help me with these ,how can i connect and make query through budibase to mongodb??

**Comment by pavleks** [comment]
Hi @mituBarua I am playing with Budibase myself and might be able to help you with this. I made a short video showing the connection process.  I assumed you are using the cloud version of Budibase and you have your mongodb connectionstring. If otherways please let me know. 

https://user-images.githubusercontent.com/76126966/151806073-3065aca5-db91-42d6-aea1-42d874008a3d.mp4

**Comment by mituBarua** [comment]
Hi Alex Pavliv,
I felt gratitude for your quick response, I am using mongodb and budibase
through docker , and facing this error, I have attached screenshot of error

**Reply by pavleks** [reply]
@mituBarua I cant see a screenshot for some reason, please could you reupload it?

**Reply by mituBarua** [reply]
![WhatsApp Image 2022-01-31 at 8 22 55 PM](https://user-images.githubusercontent.com/64905702/151812662-df02efb0-cbdb-40f9-9de5-5a248dd248f4.jpeg)
![WhatsApp Image 2022-01-31 at 8 24 02 PM](https://user-images.githubusercontent.com/64905702/151812671-7953fb88-7206-49b8-830a-399e77fac739.jpeg)

**Reply by pavleks** [reply]
@mituBarua As I know Budibase team hardcoded 10 seconds timeout for all the queries.  You could change it in your `docker-compose.yaml` adding  `QUERY_THREAD_TIMEOUT: 10000` change the number to the one you want and restart the stack.  It might help.

```
# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    ports:
      - "${APP_PORT}:4002"
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      QUERY_THREAD_TIMEOUT: 20000
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
```
