### DISCUSSION TITLE
Google Sheet Integration - Authentication issue

### DISCUSSION THREAD

**Discussion by mervyn15** [Budibase/budibase#4471] [Help] [answered]
Hi,

I want to try the new feature for the new update v1.0.62 which has the google sheet integration. however, I am having problems in doing it. This error occurs once I click the Sign In With Google button:
{"message":"Error constructing google authentication strategy","status":500}

And then even if it seemed to have failed, the Google Sheet Datasource shows among my List of Datasources

**Comment by hendrikjap** [comment]
I have the same problem.

**Comment by shogunpurple** [comment]
Hi @mervyn15 and @ely2727 - do you have your google authentication credentials set up in your self hosted instance? You will need to configure 2 environment variables in your instance in order to use the integration:

`GOOGLE_CLIENT_ID`
`GOOGLE_CLIENT_SECRET`

If you are running docker-compose, the easiest way to add these is through your `docker-compose.yaml`:

```
  worker-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    ports:
      - "${WORKER_PORT}:4003"
    environment:
      GOOGLE_CLIENT_ID: xyz
      GOOGLE_CLIENT_SECRET: xyz
```

It does sound like an issue here in that it should try to use your google auth config in the builder, then fall back to the environment variables if that isn't present. Will look into this

**Reply by hendrikjap** [reply]
Hi @shogunpurple , I don't have that google client line in my `docker-compose.yaml`

Do I have to manually enter it? Is it more user-friendly if we can use Google Sign-in option directly on the builder rather than the backend?

**Reply by mervyn15** [reply]
Thank you for your guidance, I added these lines in my  docker-compose.yaml. However, after going through the Google sign in, there will be a portion where Google will ask for your permission to allow the spreadsheet access. I pressed the continue button but then it only goes to a page not found screen. 

I would like to ask if there is a special access/scope that we should configure in the google console?
Thank you

**Reply by hendrikjap** [reply]
They will officially support Google Sheets in February release! Just wait for few more weeks.

**Reply by robpegurri** [reply]
I have exactly the same issue, i see a "Not found" page

**Reply by shogunpurple** [reply]
@ely2727 - the google sign in option is in the builder - but you have to use your own google credentials, like all other self hosted software. Once we release google sheets to the cloud, this is not the case. 

@RobertPegu @mervyn15 i will look into this issue - it appears that there may have been a regression here. Thanks!

**Comment by lollococce** [comment, marked as answer]
Hi!

Any news? I added for self-hosted the creds and env vars to the container, the same of the SSO GSign in (enabling Gsheet API) but still nothing - I added this redirect URI : {my-domain}/api/global/auth/default/datasource/undefined/api/global/auth/datasource/google/callback on the Google API console Creds

But when I give consent the response is `Not Found` on the webpage and the same URI with some GET options after the `?` as a response : code, scope etc

When I try a GSheet ID still getting an `Cannot read property 'accessToken' of undefined` cause I could not have the auth step before properly working

**Reply by shogunpurple** [reply]
Hi @lollococce - seeing the same issue, where the URL seems to have doubled up. This could be down to our recent switch over to NGINX, where an extra URL is getting appended and causing it to fail. We will have a fix out in the coming days. Thanks!

**Reply by robpegurri** [reply]
> Hi @lollococce - seeing the same issue, where the URL seems to have doubled up. This could be down to our recent switch over to NGINX, where an extra URL is getting appended and causing it to fail. We will have a fix out in the coming days. Thanks!

Any news about this? I've updated Budibase to the latest version but I still get the same "Not found"

**Reply by lollococce** [reply]
Hey @RobertPegu ! Yes still getting "Not Found" with BB 1.0.110

**Reply by shogunpurple** [reply]
Hi folks - so the 404 issue above has been fixed and pushed a while ago. I looked into this other problem locally and realised that the problem in self host is the reliance on the `PLATFORM_URL` environment variable - you should be able to fix this by adding your `PLATFORM_URL` to the worker-service in your docker-compose file.

```
worker-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    ports:
      - "${WORKER_PORT}:4003"
    environment:
      PLATFORM_URL: "https://yourbudibaseurl"
```

What we can do is read this directly from the platform URL that you can view in the portal, so the environment variable won't be necessary - we will get this pushed over the next few days and it will be in the next release. Thanks!

**Reply by robpegurri** [reply]
It worked, thanks @shogunpurple

**Comment by ddeepak95** [comment]
I'm facing another issue. The redirecturi in the budibase is in **http** whereas Google console accepts only **https**. Can someone please help?

**Reply by shogunpurple** [reply]
@ddeepak95 if running self hosted, you can update your `Platform URL` of budibase to change where the redirects occur. You'll find this in the `Organization` tab in the budibase portal. 

Although generally if running self hosted, you should be running your setup over HTTPS anyway - more information about how to set that up here: https://docs.budibase.com/docs/reverse-proxy

**Reply by rohanrajpal** [reply]
Hey, I'm on a reverse proxy via caddy & have set the platform url here: 
![image](https://user-images.githubusercontent.com/7023147/165361959-68a073f6-ceb4-4036-8ad3-3487f883d3e3.png)

Still, I'm getting HTTP in the redirect URI:
![image](https://user-images.githubusercontent.com/7023147/165362072-a6d8fab8-9be2-4873-9c2c-a5794add345b.png)

```
 worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PLATFORM_URL: https://budi.spurchat.tech
    depends_on:
      - redis-service
      - minio-service
      - couch-init
```
