### DISCUSSION TITLE
Docker security best practices setup - exposed ports? eek!

### DISCUSSION THREAD

**Discussion by datdamnzotz** [Budibase/budibase#4492] [Show and tell]
I'm looking over the deployment I don't like seeing exposing ports when I don't have to.
Looks like the app runs everything through the proxy anyways so ... ? eek!

I'm thinking that none of these services need to be exposed outside the host:
https://github.com/Budibase/budibase/blob/develop/hosting/docker-compose.yaml#L10-L11
https://github.com/Budibase/budibase/blob/develop/hosting/docker-compose.yaml#L38-L39
...

Better solution would be docker in swarm mode with a network for all the services to lay in services, not so they can be scaled, but they get the advantage of docker networks.  

Now you could probably do a network or two in a non swarm configuration just the same but I went with swarm deploy so I have high availability. (So I didn't even look at non-swarm network setups)

## Current setup:

Each app is bound to the hosts IP and exposed by default to the network that the host is on. If that is a public IP on the interwebs this isn't a good idea.

Here you can see all the ports bound to the host IP. eek.

![image](https://user-images.githubusercontent.com/3913859/153941190-8f32e532-0c80-4c01-8743-0f5411205ab3.png)

## Proof of concept:
(well actually I am using this in production after a few days of fiddling with it)

I would recommend to anyone running this stack to update to this conf.  It is more secure because redis, crouchbase, etc are not exposed at all.  They are not bound to the host's IP, they are in an internal network that only the application can see.  
(Dev guys take this with a grain of salt if you are talking directly to those services, this will kill your access to those services)

As you can see the only service that is exposed is the proxy:
![image](https://user-images.githubusercontent.com/3913859/153939897-465f7891-6bf7-46ca-9936-e5a312323886.png)

### Storage
Couple things to consider when running in swarm mode is your storage and where it is mounted.  
For a single node in the swarm you can skip these steps the config below this section will just fine.
If you have more than one node you can do one of two things.  

Attach to shared storage for each of the volumes listed in the compose file (either SMB or NFS works) so each node can access it (high availability if a node goes down)

SMB
```
volumes:
  data:
    driver_opts:
      type: "cifs"
      device: "//192.168.1.10/data"
      o: "addr=192.168.1.10,rw"
      o: "uid=0,username=samba-username,password=samba-password,file_mode=0770,dir_mode=0770"
```
NFS
```
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/nfs/data"
```

**Those shares have to be highly available. It always has to be there before docker starts.**
**Don't do this if someone reboots that server on a daily bases.**

### -or-

Or add the tags to each container to force it to a node and it will create volumes on that node and launch ONLY on that node.
https://docs.docker.com/engine/swarm/services/#placement-constraints
Probably best for smaller environments that are 1 nodes or you don't care about uptime.
Note: this is not highly available since the storage is local to the node.   Really only do this if you have one node.

If you want to change this in the future, remember the storage is local to that node, you will have to copy it to the new node before starting the app on the new node.

```
    deploy:
      placement:
        constraints:
          - node.hostname == node01
```

## Setup your swarm
`docker swarm init` 
(done once)

### Proposed Budibase docker stack deployment.

`docker stack deploy -f docker-compose-stack.yaml`

(or if you use portainer just copy paste into a new stack and import your .env)

```
version: "3"
# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: app-service
    #ports:
    #  - "${APP_PORT}:4002"
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
# Not supported in swarm
#    depends_on:
#      - worker-service
#     - redis-service
    networks:
      - budibase

  worker-service:
    restart: always
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    #ports:
    #  - "${WORKER_PORT}:4003"
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      #SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
#    depends_on:
#      - redis-service
#      - minio-service
#      - couch-init
    networks:
      - budibase

  minio-service:
    restart: always
    image: minio/minio
    volumes:
      - minio_data:/data
    #ports:
    #  - "${MINIO_PORT}:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - budibase

  proxy-service:
    restart: always
    container_name: bbproxy
    image: budibase/proxy
    #image: envoyproxy/envoy:v1.16-latest
    #volumes:
    #  - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "${MAIN_PORT}:10000"
#    depends_on:
#      - budibase_minio-service
#      - worker-service
#      - app-service
#      - couchdb-service
    volumes:
#    I rolled my own here but you can keep the default
#    download and configure nginx settings either from https://www.digitalocean.com/community/tools/nginx
#    or pull the default files from https://github.com/nginx/nginx/tree/master/conf Missing mime.types
      - proxy_data:/etc/nginx/
    networks:
      - budibase

  couchdb-service:
    restart: always
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    #ports:
    #  - "${COUCH_DB_PORT}:5984"
    volumes:
      - couchdb3_data:/opt/couchdb/data
    networks:
      - budibase

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
#    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]
#    since we are in swarm mode we don't want the service to keep respawning the couch-init, just run it once and sleep
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; sleep infinity;"]

    networks:
      - budibase

  redis-service:
    restart: always
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    #ports:
    #  - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - budibase

  watchtower-service:
    image: containrrr/watchtower
    #ports:
    #  - "${WATCHTOWER_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - budibase

networks:
  budibase:

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  proxy_data:
    driver: local
  redis_data:
    driver: local
```

### Start up order

Observations shows that the proxy comes up and dies (due to time outs reaching the app) and restarts a few times before launching.
So you end up with a container or two that is in a stopped state.
![image](https://user-images.githubusercontent.com/3913859/153934900-37809eee-8dc6-4629-98da-f8f7efece755.png)

Based on Docker's recommendations 
https://docs.docker.com/compose/startup-order/

The dockerfile launch scripts for each service are going to need something like 
https://github.com/vishnubob/wait-for-it
to validate their dependences before launching down the road.   Which probably wouldn't hurt a non swarm setup either. 

e.g.
```
FROM nginx:latest

RUN apk add --no-cache bash
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["/wait-for-it.sh", "app-service:4002", "--", "nginx", "-g", "daemon off;"]
```
Comments are most welcome : ]

**Comment by Shyru** [comment]
We also stumbled over this during the deployment via docker-compose. I wondered if I could set the ports to an empty string in the properties file. I think that would be the easiest way and the default properties-file should have them set to nothing so that it is secure by default.

**Comment by aptkingston** [comment]
@datdamnzotz your timing is very coincidental! I actually went through setting up the stack on my own server yesterday (also using portainer) and raised a lot of the same considerations internally with the team. I wasn't considering swarm, so my notes just consider a typical compose setup.

I'm going to paste my writeup here for reference:

- Most of the containers don't need internet access, so would be better configured with an internal docker network only, for security. Only the proxy and the apps service (for pulling templates etc) need internet access
- Binding container ports to the host is unnecessary (apart from the proxy) as the rest of the comms are done between direct container hostnames, as long as they're on the same docker network
- Cleanup of the UIDs and GIDs would be nice, as most containers will run as root but redis seems to write as systemd-coredump and couchdb runs as 1001:1001
- I'm not a fan of giving watchtower full access to my docker.sock, so I wanted to remove the watchtower container from the stack entirely. I had to manually override the nginx.conf to do this as nginx won't start if it can't resolve an upstream host name on boot (you can get around this by using variables, as long as you set a resolver directive). This is really just my problem since i wanted to remove it
- I'd prefer if we pinned versions of images to avoid versions changing every time we run the stack, and control updates manually. But that's just me - I'm not a fan of automatic container updates or watchtower.
- I wanted to customise the container names which was hard but possible as long as you make sure to find every single reference, including inside the nginx conf
- Having env settings for stuff like MINIO_PORT, REDIS_PORT, COUCH_PORT etc are redundant since comms are done directly by container hostname, and we don't need to bind them to the host. These could be removed. Only MAIN_PORT is needed
- There's a local ./log directory binding which isn't mounted as a docker volume. I use local binds anyway, but could easily have missed this since the rest of the compose file uses docker volumes
- In general I think we should use unless-stopped rather than always as a restart policy
- I had to increase the nginx rate limiting burst to 20, otherwise i get multiple 503s when creating an app, which causes the builder not to navigate to the new app
- Since we build the proxy image ourselves, we could use that to replace the functionality of the `couch-init` container, and then remove that entirely

**Reply by datdamnzotz** [reply]
@aptkingston @Shyru Both of you have awesome feed back! 
I am still learning what the the containers do as I just started looking at this app a couple weeks ago.

Anything else security wise ?

On my list: 

- Figure out UIDs and GIDs and build users for them
- We removed watchtower (as we have our own already - a change control process - reporting what needs upgrading, not automated just for reporting and change requests to upgrade etc )  We use https://hub.docker.com/r/fluencelabs/docker-socket-proxy on the swarm so it shields the docker daemon (traefix and watchtower talk to this) I left it in above as it was part of the community image.  Depending on how upgrades go this may go automated in the future to keep containers up to date.
- Move all the .env stuff to secrets and hard code the port/names
- Saw the ./log and just removed it (as above)
- couch-init seems to only create the db?  I'm not sure if it is used to trigger background tasks or ? Might just remove it.
- nginx currently we have set to rate limit @ 40 (might bump it to 50 if we have problems still looking at building apps with this guy) see #4481 
- implement traefik instead of nginx : ] with the rate limits as we are a traefik shop and use letsencrypt via traefix just simplifies cert management. Short term we are just going traefix -> nginx. long term we will go traefix -> the app,  Have to figure out all the reverse proxy paths.  I was sad to see it hasn't been done yet as this takes lots of testing to get it right.
- Agreed - unless-stopped rather than always as a restart policy

### Other things I am looking at
adding the following line makes sure that the containers do not gain additional privileges:
```
    security_opt:
      - no-new-privileges:true
 ```
Resource limiting - if anyone has some starter recommendations for the app itself that would be awesome.
Setting resource limits in Docker Swarm mode:
```
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '1'
          memory: 200M
```
Run the containers through Docker Bench and Clair
https://github.com/docker/docker-bench-security
https://github.com/quay/clair
