### DISCUSSION TITLE
Data Backup with Digital Ocean Snapshots

### DISCUSSION THREAD

**Discussion by ghost** [Budibase/budibase#4837] [Help] [answered]
I want to get Budibase setup on Digital Ocean in a way that is easy to backup and restore. I have somewhat limited experience with Docker and Digital Ocean.

I plan to setup a single Docker Droplet with an External Storage Volume and then configure the Budibase Docker configuration to map the volumes for CouchDB and MinIO to the External Storage Volume.

I believe this should make it easy to:

- Snapshot the application server and the storage volume whenever I do upgrades to Budibase or server configuration.
- Snapshot the external storage volume on a schedule to backup just the data

Is using Snapshots with an External Storage Volume an effective way to ensure my Budibase data is backed up for disaster recovery?

**Comment by shogunpurple** [comment]
Hey @kawfeebassie,

Good discussion - thanks for taking the time! I think it might be good to explore a few options here, just so other people can get some ideas if they want to do the same thing. 

Here are a few backup and restore options in terms of difficulty:

### (Easiest) Direct Snapshot from DO
https://docs.digitalocean.com/products/images/snapshots/

This will take a full disk image of your droplet, including everything. This is easy, but it could get expensive as you have to pay for your snapshots. These are easy to restore and use, but maybe a little heavyweight for what you are trying to do. They aren't really disk backups as much as they are full VM snapshots.

### (Intermediate) Block/External Storage Volumes
As you mentioned in your proposed approach, you can add block storage to your digitalocean droplet on creation.
![Screenshot 2022-03-08 at 09 51 35](https://user-images.githubusercontent.com/11256663/157201468-f729fd2f-34cc-41f8-a519-f560ab5583ec.png)

You can then back **only** this storage up in a snapshot, rather than the whole droplet. This is a more flexible option, as it allows you to share the data across different droplets. You also don't have to update any docker configuration - this should just work out of the box as all the volume data will be stored on disk.
https://docs.digitalocean.com/products/images/snapshots/how-to/snapshot-volumes/

### (Advanced) Using Docker Bind Mounts and your own backup tools
You could also backup your data only by updating the `docker-compose.yaml` file in budibase to use [docker bind mounts](https://docs.docker.com/storage/bind-mounts/) to actually write the data from each service to a directory on disk, rather than wrapped up in docker volumes. Here's an example of how you would do this with the `couchdb` service.

```
  couchdb-service:
    restart: always
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - /some/absolute/path:/opt/couchdb/data
```

You can then use whatever tools you want to backup  the directories that you want. 2 good options:
- https://rclone.org/
- https://restic.readthedocs.io/en/latest/

The nice thing about this setup is that it provides total flexibility and you can schedule the backups easily with things like cron jobs.

Hope this helps!

**Comment by ghost** [comment, marked as answer]
Thank you for the information @shogunpurple. I did some digging and I think I found some common ground between what you are describing as the Intermediate and Advanced options.

The current Budibase [docker-compose.yaml](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml) defines three named volumes for persisting data.

```
volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```

**INTERMEDIATE - CHANGE DOCKER DATA ROOT**

To get the Budibase docker-compose configuration to work without changes, you would need to change **data-root** for docker on the host Droplet to point to the mounted external storage volume. This can be done by stopping the docker service, and then updating the **/etc/docker/daemon.json** file:

```
{
 //...
 "data-root": "/mnt/ext-storage",
 //...
}
```

This puts all Docker storage on the external storage volume. When starting Budibase, this will put all the container images, and all the named volumes on the external storage volume. This is a satisfactory option, but I don't really want the docker images on the external storage volume, just the data volumes.

**ADVANCED - EXTERNAL NAMED VOLUMES**

To implement the advanced option using Docker named volumes instead of Docker bind mounts, you can change the compose file to indicate the named volumes alternate device location:

```
volumes:
  couchdb3_data:
    driver: local
    driver: opts:
      type: none
      o: bind
      device: /mnt/ext-storage/couchdb3
  minio_data:
    driver: local
    driver: opts:
      type: none
      o: bind
      device: /mnt/ext-storage/minio
  redis_data:
    driver: local
    driver: opts:
      type: none
      o: bind
      device: /mnt/ext-storage/redis
```

Alternatively, if you want to avoid hard-coding the local file-system path in the compose file, you can indicate the volume is created externally:

```
volumes:
  couchdb3_data:
    external: true
  minio_data:
    external: true
  redis_data:
    external: true
```

Then you can use the Docker CLI to manually create the named volumes and map them to the external storage volume.

```
docker volume create --driver local \
    --opt type=none \
    --opt device=/mnt/ext-storage/couchdb3 \
    --opt o=bind couchdb3_data

docker volume create --driver local \
    --opt type=none \
    --opt device=/mnt/ext-storage/minio \
    --opt o=bind minio_data

docker volume create --driver local \
    --opt type=none \
    --opt device=/mnt/ext-storage/redis \
    --opt o=bind redis_data
```

Then only the Docker data volumes will be placed on the external storage volume. From there you can use directory/file backup options and CRON to also periodically backup up the data volumes in case of corruption and/or external storage volume snapshots.
