### DISCUSSION TITLE
Access to MinIO issue

### DISCUSSION THREAD

**Discussion by samg666** [Budibase/budibase#5084] [Help] [answered]
Hello,

I am trying to access MinIO and followed below guide [https://docs.budibase.com/docs/accessing-minio](url), turned `docker-compose.yaml` `MINIO_BROWSER: "on"`, then restarted docker and server, but still not able access via URL `your-budibase-host/minio`. 

My budibase URL `http://192.168.100.14:10000/`, tried access via `http://192.168.100.14:10000/minio` or `http://192.168.100.14:9000/` or `http://192.168.100.14:9000/minio`, all not work. Could someone give some help?

BTW, the reason why I want to access MinIO is I am going to migrate my Budibase, then I am thinkg to backup the uploaded files and move to my new Budibase manually. Is this a right way, or any other suggestion?

**Comment by melohagan** [comment, marked as answer]
Try updating the **minio-service** section of the docker-compose.yaml with the following:

```
ports:
      - "9000:9000"
      - "9001:9001"
```

```
command: server --console-address ":9001" /data
```

Let me know if that resolves your issue!

**Comment by samg666** [comment]
Hi @melohagan , thanks for you reply. I have recently upgrade Budibase, and found there's no `ports` config on the new `docker-compose.yaml`.  I have turned on `MINIO_BROWSER: "on"`, but still not able to access `http://192.168.100.14:9000/` or `http://192.168.100.14:10000/minio` (my Budibase running on `http://192.168.100.14:10000`). If I access via `http://192.168.100.14:10000/minio`, then the browser being redirected to `http://192.168.100.14:46577/`.

Actually, the reason why I want to access MinIO is I am going to migrate my Budibase, and I have some uploaded files needs to be migrate as well. Is there any better way to migrate the upload files?

## Below are the new docker-compose.yaml minio-service config
```
  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "on"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

**Reply by melohagan** [reply]
The ports are missing from the new docker-compose.yaml but try adding them in, and also update that command line as well. 

So your config should look something like:

```
minio-service:
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "on"
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

If that works for you, then I can ask the devs if those ports should be included in the docker-compose file going forward.

**Reply by samg666** [reply]
@melohagan Thank you very much for your help. It works after replaced `minio-service` as you have provided. 

![image](https://user-images.githubusercontent.com/29649651/162715382-e587b009-d9f6-4cd5-b703-46146e090cc0.png)

**Reply by samg666** [reply]
@melohagan If I would like to migrate my Budibase, what is the right way to migrate my MinIO attachments? I have study on the MinIO console, it seems there's no export/import features. Appreciate if you can provide some help on this. Thank you.

**Reply by melohagan** [reply]
@ggs331 As the minio service is containerised, you may be able to migrate your docker volume and remount (https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes) 
There is an issue open for better handling attachment exports in the future: https://github.com/Budibase/budibase/issues/3378

**Reply by samg666** [reply]
> @ggs331 As the minio service is containerised, you may be able to migrate your docker volume and remount (https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes) 
> 
> There is an issue open for better handling attachment exports in the future: https://github.com/Budibase/budibase/issues/3378 

thank you very much, I will try.

**Reply by MrGonzo1024** [reply]
Hi @melohagan  

I am having a similar issue. I have the DigitalOcean implementation of Budibase and upgraded to the latest version. I've made the changes to the minio-service section of the docker-compose.yaml file exactly as you described.

```
minio-service:
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "on"
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```



But I'm still getting the following error when I try to access minio via http://my_ip_address:10000/minio 

```
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this resource has been disabled.</Message>
<Resource>/minio</Resource>
<RequestId/>
<HostId>8da2a24f-0436-4b82-b4b4-342c62809ac3</HostId>
</Error>
```
I restarted docker-compose. I've even restarted the server. I also verified the configuration with "docker-compose config" command. Same error.  I'm at a loss. Any ideas how I can troubleshoot?

Thanks!
