### DISCUSSION TITLE
Building from source for production with docker compose

### DISCUSSION THREAD

**Discussion by daawaan4x** [Budibase/budibase#5434] [Help]
In the documentation, the docker compose for production uses the official images for the app from Budibase. Is there a way to build from a modified source to run for production with docker compose?

**Comment by mike12345567** [comment]
Hi @daawaan - you've got two choices here:

1. You can modify the docker-compose script to build the server Dockerfile instead of using a pre-built image, for example you can do:
remove the `image` tag from the yaml
```
app-service:
  image: custom-app-image
  build:
    context: ../packages/server
    dockerfile: ../packages/server/Dockerfile
```

If you run a `yarn build` beforehand this should build a custom image on your machine which you can run from.

2. To use this outside of a development environment you might want to build the image and publish a custom version yourself, in the server `package.json` command you can see our `build:docker` command which generates an image, then you can put that image up to docker hub or your preferred container registry solution (ECR, ACR etc).
