### DISCUSSION TITLE
How to setup a custom domain

### DISCUSSION THREAD

**Discussion by oitkenmen** [Budibase/budibase#5435] [General]
(if you're self-hosting using Kubernetes on AWS EKS)

**Comment by mjashanks** [comment]
Hi @berkimbayev - It's the weekend, and we have a public holiday for easter, so it will be Tuesday **at the earliest** until you get a reply.

I see you've also posted several times here: https://github.com/Budibase/budibase/issues/5449

This is community (free) support. We generally have a great response time in here and are happy to support our community. However, you have to accept that it could be several days - please do not repost repeatedly, this is just rude.

More than happy to offer a quicker response time under a paid support contract - please contact sales@budibase.com

**Comment by oitkenmen** [comment]
Hello. I've made it with this command: ```kubectl edit ingress -n budibase```. In the editor, I've changed to this:

```
spec:
  rules:
  - host: (domain)
    http:
      paths:
      - backend:
          service:
            name: proxy-service
            port:
              number: 10000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - (domain)
    secretName: tls-secret
status:
  loadBalancer:
    ingress:
    - hostname: (randomsymbols).(region).elb.amazonaws.com
```

Then, I've found the LoadBalancer's CLUSTER-IP using this command: ```kubectl get services -n budibase``` and added it as an A record. Also, I've added the default URL to the self-hosted app (randomsymbols.region.elb.amazonaws.com.) as a CNAME record. It worked. Please, let me know if I did something wrong.
