### DISCUSSION TITLE
How to install an SSL certificate if AWS EKS

### DISCUSSION THREAD

**Discussion by oitkenmen** [Budibase/budibase#5646] [Show and tell]
Hello,

This is just a description of how I've installed an SSL Certificate on Budibase deployed on AWS EKS. For future reference. If I made it wrong or made any mistakes, please write below. This description is based on this article: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes

1. First, I've installed cert-manager: `kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml`

2. Checking that cert-manager was installed and running: `kubectl get pods --namespace cert-manager`

3. Creating certificate issuer: `nano issuer.yaml`

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: # !!! write your email here !!!
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
```

4. `kubectl create -f issuer.yaml`

5. Editing ingress to add the certificate: `kubectl edit ingress -n budibase`

a) addding annotation:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
```

b) adding tls:

```
spec:
  tls:
  - hosts:
    - (your custom domain here)
    secretName: tls
```

6. Checking the website if HTTPS is working.
