### DISCUSSION TITLE
Disable version auto update

### DISCUSSION THREAD

**Discussion by ryzam** [Budibase/budibase#7009] [Help] [answered]
Hi guys, Currently I'm running budibase app project in production mode, but as a new version been release it will automatically update budibase engine to the new version and this sometime quite risky because sometime there is a function/UI break when running in new version.

**Comment by shogunpurple** [comment, marked as answer]
Hi @ryzam - this should not be happening, as the default `docker-compose.yaml` is not set up for auto update - generally this is caused by having configuration in your watchtower container for auto updating:

If you update your `docker-compose.yaml` `watchtower` entry to look like the following:

```
watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

Then you can run `docker-compose up -d` to make the configuration changes take place. 

You will only update if you go to the `Updates` tab and click the button to update. Do you possibly have an old version of the `docker-compose.yaml` in your installation?

Thanks!
