### DISCUSSION TITLE
Budibase behind proxy

### DISCUSSION THREAD

**Discussion by rolandwang19** [Budibase/budibase#7052] [General]
I'm using Budibase on a Centos7 server and am trying to connect to the corporate proxy to access the internet. I've set the GLOBAL_AGENT_HTTP_PROXY and GLOBAL_AGENT_HTTPS_PROXY in my docker-compose file under environment like below.

```
services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init
```

When it runs, I saw that my app container is stuck as restarting and doesn't actually run. I checked the log for the container and found the following.

```
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.32s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.10s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.38s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.07s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.07s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.12s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.06s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.10s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.25s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.19s.
```

The container is able to start when the proxy variables are not set. Only see this when they are. If I try to access the app while it's in this state, I get a 502 error.

![image](https://user-images.githubusercontent.com/10952866/182517654-3e3a4133-340b-4c8b-bc5a-c971c9234286.png)

**Comment by ThomasK33** [comment]
You need to add a `GLOBAL_AGENT_NO_PROXY` variable containing the budibase services and database names, i.e., `app-service,worker-service,[...]`, as otherwise those requests get proxied instead of remaining in the docker network.

**Reply by rolandwang19** [reply]
Still getting the same error. I'm able to curl using the container and connect, so not sure what's wrong with the config that's not working.

![image](https://user-images.githubusercontent.com/10952866/182843405-ae2da8ed-0dea-4166-aa51-f22df14f7c16.png)


Tried to implement what I think you said, but might be misinterpreting. 

```
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_NO_PROXY: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984,http://app-service:4002,http://worker-service:4003,http://minio-service:9000,https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131,redis-service:6379,http://localhost:9000/minio/health/live
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_NO_PROXY: http://minio-service:9000,http://app-service:4002,http://worker-service:4003,http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984,https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131,redis-service:6379,http://localhost:9000/minio/health/live
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```

**Reply by ThomasK33** [reply]
`NO_PROXY` (and the global agent prefix) requires hostnames, not URLs.

See curl for reference: https://curl.se/docs/manual.html#environment-variables

You should try:
```yaml
GLOBAL_AGENT_NO_PROXY: couchdb-service,app-service,worker-service,minio-service,redis-service,localhost
```

**Reply by rolandwang19** [reply]
Gave it a shot, still getting the same error.

```
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_NO_PROXY: couchdb-service,app-service,worker-service,minio-service,redis-service,localhost
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_NO_PROXY: couchdb-service,app-service,worker-service,minio-service,redis-service,localhost
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```
