### DISCUSSION TITLE
How to connect top level domain as a custom domain? (if AWS EKS)

### DISCUSSION THREAD

**Discussion by oitkenmen** [Budibase/budibase#7388] [Help]
Hello to everybody. Is there any way to point an ingress controller to the main domain, not to the subdomain? What do I need to write into DNS records? My current ingress file looks like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ...
  labels:
    ..
  name: budibase-budibase
  namespace: budibase
spec:
  rules:
  - host: (subdomain)
    http:
      paths:
      - backend:
          service:
            name: proxy-service
            port:
              number: 10000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - (subdomain)
    secretName: (secretName)
status:
  loadBalancer:
    ingress:
    - hostname: (something).(region).elb.amazonaws.com
```

**Comment by shogunpurple** [comment]
Hi @berkimbayev - I'm not quite sure what you are asking here. Assuming that you have configured cert-manager and the other pre-reqs for setting up a TLS enabled ingress in kubernetes, and If you are configuring your own ingress, you should be able to use a pretty standard configuration for that. If you want to set up your top level domain and some subdomains, you should be able to use something like the following:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatever
spec:
 tls:
  - hosts:
      - yourdomain.com
      - subdomain.yourdomain.com
    secretName: your-tls-secret
  rules:
  - host: yourdomain.com
    http:
      paths:
      - backend:
          serviceName: proxy-service
          servicePort: 10000
  - host: subdomain.yourdomain.com
    http:
      paths:
      - backend:
          serviceName: proxy-service
          servicePort: 10000
```

As for setting up your DNS records - before you deploy this, cert-manager needs to be able to access the server on the domain in order to verify the DNS records. You will need to set:

**A Record** - yourdomain.com -> load balancer IP
**CNAME record** - subdomain.yourdomain.com -> yourdomain.com OR another A record if you want it to point somewhere else.

Hope this helps.
