### DISCUSSION TITLE
REST API - Self signed certificates

### DISCUSSION THREAD

**Discussion by 4nsix** [Budibase/budibase#7424] [Help] [answered]
Hi,

i have already tried this: https://github.com/Budibase/budibase/discussions/3917
But no success. i still get the error: Query Error: request to https://name.local:3000/examples? failed, reason: self signed certificate

Please help

**Comment by Rory-Powell** [comment, marked as answer]
Hi @dwesthuis , did you also add the certificate to the `app-service` container?
if so, are you able to ssh into the container and run a `curl` command against the endpoint you are trying to connect to, does it have the same error?

**Reply by FocusDesigner** [reply]
Hi @Rory-Powell as I had the same problem, I tried your solution with a kind of progress. I now get a different error

`Query Error: request to https://xxx? failed, reason: Parse Error: Missing expected CR after header value`

`curl ` works, but only with option `-k`

**Reply by Rory-Powell** [reply]
Are you able to curl the endpoint without the -k flag from another shell outside the container? If not it would indicate the certificate is invalid for the connection being made, if so it would indicate the certificate isn't being loaded into the container correctly

**Reply by 4nsix** [reply]
> Hi @dwesthuis , did you also add the certificate to the `app-service` container?
> if so, are you able to ssh into the container and run a `curl` command against the endpoint you are trying to connect to, does it have the same error?

Yes, it works now!

**Reply by FocusDesigner** [reply]
@Rory-Powell the certificate seems fine to me as it works everywhere when used directly with `curl --cacert cacert.crt`  The mountpoint does work as well, the cert is visible in both containers. So the only possible error left  is the `NODE_EXTRA_CA_CERTS: /app/cacert.crt` does not work correctly, as far as I understand it. Do I have to install something to make that work?

here is my compose file as a reference:

```
services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      NODE_EXTRA_CA_CERTS: /app/cacert.crt
    depends_on:
      - worker-service
      - redis-service
    volumes:
      - /home/admin/fw.crt:/app/cacert.crt

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      NODE_EXTRA_CA_CERTS: /app/cacert.crt
    depends_on:
      - redis-service
      - minio-service
      - couch-init
    volumes:
      - /home/admin/fw.crt:/app/cacert.crt
```

I tried different mountpoints, but that doesn't make a difference.
I'm using the portainer version of budibase, if this is somehow relevant
