### DISCUSSION TITLE
Unable to access MinIo

### DISCUSSION THREAD

**Discussion by abder78000** [Budibase/budibase#7808] [Help] [answered]
I can't connect to MinIO despite having completed all the steps in the [documentation](https://docs.budibase.com/docs/accessing-minio)
When I type: my-budibase-host/minio, I get the following error:

`<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this resource has been disabled.</Message>
<Resource>/minio</Resource>
<RequestId/>
<HostId>e2vc8e39-297a-312a-a59d-42f12012b62e</HostId>
</Error>`

**Comment by melohagan** [comment]
Hey @abder78000 

I think you may have missed the step were you need to enable the MinIO Browser: https://github.com/Budibase/budibase/discussions/5084#discussioncomment-2541477

```yaml
minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "on"
```
