### DISCUSSION TITLE
413 Request Entity too large

### DISCUSSION THREAD

**Discussion by charlesdsmith** [Budibase/budibase#8251] [Help] [answered]
I'm receiving this error when I am trying to POST a big payload from budibase to my one of my query data sources. I've check the logs for my API and I'm not seeing this error. Is this a problem that can be fixed in my Budibase config? 

Thank you

![image](https://user-images.githubusercontent.com/38652599/195686896-ffaf2c0b-8136-4fc5-8909-69d314f55ad4.png)

I also can't find where my nginx.conf is located

**Comment by charlesdsmith** [comment, marked as answer]
@shogunpurple Hey sorry to bother you but any insight on this? I have a reverse proxy with Caddy and I'm self hosting, not sure where any configuration file is located that I can edit.

Thank you in advance

**Reply by shogunpurple** [reply]
https://github.com/Budibase/budibase/discussions/4912

**Reply by charlesdsmith** [reply]
thanks for the reply, where is that nginx conf located? there's nothing in /etc/ for me. I'm also using caddy for the reverse proxy not sure if that matters

**Reply by shogunpurple** [reply]
If you search `nginx` in discussions it's the top hit. Here https://github.com/Budibase/budibase/discussions/8028

Caddy shouldn't matter unless you have file size limits in there also

**Reply by charlesdsmith** [reply]
Yea that directory doesnt seem to exist for me, that is: `/etc/nginx/templates/nginx.conf.template`

**Reply by shogunpurple** [reply]
Are you looking at it in the docker container? What commands are you running to check?

**Reply by charlesdsmith** [reply]
I've just ssh'd into my EC2 instance, im self-hosting. So I just navigated to me /etc/ folder but I do not see anything

**Reply by shogunpurple** [reply]
Budibase uses docker.. so you have to find the file inside the docker container. It won’t be on your machine - did you set up the bind mount as detailed in that discussion? If you did you will see the file there

**Reply by shogunpurple** [reply]
The commands you need to follow are in the discussion, did you follow them?

https://github.com/Budibase/budibase/discussions/8028#discussioncomment-3824689

**Reply by charlesdsmith** [reply]
Ah it seems I made a mistake when interpreting where I should be operating from, I was only in my machine. I'm in the bbproxy service, and I've edited the volumes section in my docker-compose file to look like so:

![image](https://user-images.githubusercontent.com/38652599/195923524-085a5eef-f61c-45af-8b9d-e462ca12fe19.png)

Does that look right? And when I restart should I just be restarting nginx? or also `docker-compose up`?

**Reply by geertvanheusden** [reply]
@charlesdsmith Nope, that's incorrect. You need to specify the mounted volume together with the service that needs the mount (proxy-service in this case):

docker-compose.yml
```
...
proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service
    volumes:
      - /nginx_config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
  ...
 ```

Assuming `/nginx_config/nginx.conf.template` exists on the Docker host machine.

After that you should execute `docker-compose up" again.
