### DISCUSSION TITLE
How do I specify the Redis DB in the Kubernetes values.yaml Helm file?

### DISCUSSION THREAD

**Discussion by darrenpowers** [Budibase/budibase#8286] [Help] [answered]
We are using a shared AWS Elasticache instance for our Redis implementation. Each app using that Redis instance is dedicated a specific Redis DB to use. However, in the `values.yaml` file used by the Kubernetes Helm chart, I don't see a way to specify which DB Budibase should use.

Commands showing existing DB use on the Redis instance:
```
$ redis-cli -h my-redis-instace.zzimna.ng.0001.euw1.cache.amazonaws.com
my-redis-instace.zzimna.ng.0001.euw1.cache.amazonaws.com:6379> INFO keyspace
# Keyspace
db0:keys=212,expires=201,avg_ttl=13022227
db2:keys=1,expires=0,avg_ttl=0
db6:keys=6710,expires=4261,avg_ttl=4079364
db7:keys=4659,expires=1,avg_ttl=11088
db8:keys=3,expires=0,avg_ttl=0
db9:keys=21089,expires=21089,avg_ttl=213168602
db10:keys=9,expires=9,avg_ttl=446903
```

We would like to dedicate `db3` to Budibase, but I can't see where to specify that in the `values.yaml` Helm file.
The Redis section of the `values.yaml` Helm file:
```
redis:
    enabled: false # disable if using external redis
    port: 6379
    replicaCount: 2
    url: "my-redis-instace.zzimna.ng.0001.euw1.cache.amazonaws.com" # only change if pointing to existing redis cluster and enabled: false
    password: "" # recommended to override if using built-in redis
    storage: 100Mi
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.
    storageClass: ""
    resources: {}
```
