### DISCUSSION TITLE
Proxy service not finding app service

### DISCUSSION THREAD

**Discussion by darrenpowers** [Budibase/budibase#8500] [Help]
Hi Community,

We have installed Budibase using the HELM chart for K8 and using our own nginx ingress, s3 and redis managed services on AWS.

The first issue I encountered after tailing all the logs was missing system tables in CouchDB
```
budibase-couchdb-0 couchdb [notice] 2022-11-03T07:14:53.238864Z couchdb@budibase-couchdb-0.budibase-couchdb.budibase.svc.cluster.local <0.411.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
budibase-couchdb-0 couchdb [error] 2022-11-03T07:14:53.239062Z couchdb@budibase-couchdb-0.budibase-couchdb.budibase.svc.cluster.local emulator -------- Error in process <0.4167.0> on node 'couchdb@budibase-couchdb-0.budibase-couchdb.budibase.svc.cluster.local' with exit value:
budibase-couchdb-0 couchdb {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
```
I solved this with the following:
```
COUCHDBUSER=`kubectl -n budibase get secrets budibase-couchdb -o jsonpath='{.data.adminUsername}' | base64 -d`
COUCHDBPASS=`kubectl -n budibase get secrets budibase-couchdb -o jsonpath='{.data.adminPassword}' | base64 -d`
kubectl -n budibase port-forward budibase-couchdb-0 15984:5984 &
PID=`ps aux | grep kubectl | grep "15984:5984" | sed -r 's/[\t ]+/ /g' | cut -d" " -f2`
curl -X PUT http://$COUCHDBUSER:$COUCHDBPASS@localhost:15984/_users
curl -X PUT http://$COUCHDBUSER:$COUCHDBPASS@localhost:15984/_replicator
curl -X PUT http://$COUCHDBUSER:$COUCHDBPASS@localhost:15984/_global_changes
kill $PID
```

Then I got this error:
```
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "budibase-ingress-nginx-admission" not found
```
Which I solved with:
```
kubectl -n budibase delete -A ValidatingWebhookConfiguration budibase-ingress-nginx-admission
```

With those solved and the logs looking "clean" I tried to access it, but I'm getting a 502 error, "Houston we have problem" budibase screen. Also sometimes a 404 error. I see the `app-service` pod keeps restarting because the k8 readiness probe is failing so this might explain the 404 vs 502 "random" responses.  

<img width="774" alt="Screenshot 2022-11-03 at 09 21 40" src="https://user-images.githubusercontent.com/210634/199666868-a2010e06-0f2f-4436-a6e7-6291a9cb6b03.png">

Below are the logs from the `proxy-service` getting a 404 from the `app-service`
```
proxy-service-5f6c77d84-8vb4k proxy-service 2022/11/03 07:21:35 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.36.131, server: _, request: "GET / HTTP/1.1", upstream: "http://172.20.57.220:4002/", host: "budibase.....com"
proxy-service-5f6c77d84-8vb4k proxy-service 10.10.36.131 - - [03/Nov/2022:07:21:35 +0000] "GET / HTTP/1.1" 502 4363 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "10.10.38.184" response_time=1.030 proxy_host=- upstream_addr=172.20.57.220:4002
proxy-service-5f6c77d84-8vb4k proxy-service 2022/11/03 07:21:36 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.36.131, server: _, request: "GET / HTTP/1.1", upstream: "http://172.20.57.220:4002/", host: "budibase.....com", referrer: "https://budibase.....com/"
proxy-service-5f6c77d84-8vb4k proxy-service 10.10.36.131 - - [03/Nov/2022:07:21:36 +0000] "GET / HTTP/1.1" 502 4363 "https://budibase.....com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "10.10.38.184" response_time=1.013 proxy_host=- upstream_addr=172.20.57.220:4002
```

The `app-service` does not have any helpful logs, only the below and then it restarts: 
```
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
```

Looking at the `app-service` last status on k8 I see exit code 137...
```
terminated
Reason:Reason: Error - exit code: 137
Started at: 2022-11-03T09:24:18+02:00
Finished at: 2022-11-03T09:25:07+02:00
```
I can't port forward to `app-service`.

Has anyone had this issue before or can point me in the right direction on how to debug this?
I've tried changing the log level to `debug` in the HELM chart for the `app-service` but that seems to be invalid. How do I set debug logging?

This is my helm values.yaml file:
```yaml
# Default values for budibase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
# fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 10000

ingress:
  enabled: true
  aws: false
  nginx: false
  certificateArn: "arn:aws:acm:eu-west-1:376181236267:certificate/..."
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx-pvt
    kubernetes.io/tls-scheme: "true"
    nginx.ingress.kubernetes.io/client-max-body-size: 150M
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: budibase.....com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: 10000
  tls:
    - secretName: ...-tls
      hosts:
        - budibase.....com

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

globals:
  appVersion: "latest"
  budibaseEnv: PRODUCTION
  tenantFeatureFlags: "*:LICENSING,*:USER_GROUPS"
  enableAnalytics: "1"
  sentryDSN: ""
  posthogToken: "phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU"
  logLevel: info
  selfHosted: "1" # set to 0 for budibase cloud environment, set to 1 for self-hosted setup
  multiTenancy: "1" # set to 0 to disable multiple orgs, set to 1 to enable multiple orgs
  accountPortalUrl: ""
  accountPortalApiKey: ""
  cookieDomain: ""
  platformUrl: ""
  httpMigrations: "0"
  google:
    clientId: ""
    secret: ""
  automationMaxIterations: "200"

  createSecrets: true # creates an internal API key, JWT secrets and redis password for you

  # if createSecrets is set to false, you can hard-code your secrets here
  internalApiKey: ""
  jwtSecret: ""

  smtp:
    enabled: false

#  elasticApmEnabled:
#  elasticApmSecretToken:
#  elasticApmServerUrl:

services:
  budibaseVersion: latest
  dns: cluster.local

  proxy:
    port: 10000
    replicaCount: 1
    resources: {}

  apps:
    port: 4002
    replicaCount: 1
    logLevel: info
    resources: {}
    nodeDebug: "NODE_DEBUG" # set the value of NODE_DEBUG

  worker:
    port: 4003
    replicaCount: 1
    resources: {}

  couchdb:
    enabled: true
    # url: "" # only change if pointing to existing couch server
    # user: "" # only change if pointing to existing couch server
    # password: "" # only change if pointing to existing couch server
    port: 5984
    backup:
      enabled: false
      # target couchDB instance to back up to
      target: ""
      # backup interval in seconds
      interval: ""
      resources: {}

  redis:
    enabled: false # disable if using external redis
    port: 6379
    replicaCount: 2
    url: "master.....zzimna.euw1.cache.amazonaws.com:6379" # only change if pointing to existing redis cluster and enabled: false
    password: "..." # recommended to override if using built-in redis
    storage: 450Mi
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.
    storageClass: ""
    resources: {}

  objectStore:
    minio: false
    browser: false
    port: 9000
    replicaCount: 1
    accessKey: "..." # AWS_ACCESS_KEY if using S3 or existing minio access key
    secretKey: "..." # AWS_SECRET_ACCESS_KEY if using S3 or existing minio secret
    region: "eu-west-1" # AWS_REGION if using S3 or existing minio secret
    url: "https://s3.eu-west-1.amazonaws.com/budibase.....com" # only change if pointing to existing minio cluster or S3 and minio: false
    storage: 5120Mi # 5GB
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.
    storageClass: ""
    resources: {}

# Override values in couchDB subchart
couchdb:
  ## clusterSize is the initial size of the CouchDB cluster.
  clusterSize: 3
  allowAdminParty: false

  # Secret Management
  createAdminSecret: true

  # adminUsername: budibase
  # adminPassword: budibase
  # adminHash: -pbkdf2-this_is_not_necessarily_secure_either
  # cookieAuthSecret: admin

  ## When enabled, will deploy a networkpolicy that allows CouchDB pods to
  ## communicate with each other for clustering and ingress on port 5984
  networkPolicy:
    enabled: true

  # Use a service account
  serviceAccount:
    enabled: true
    create: true
  # name:
  # imagePullSecrets:
  # - name: myimagepullsecret

  ## The storage volume used by each Pod in the StatefulSet. If a
  ## persistentVolume is not enabled, the Pods will use `emptyDir` ephemeral
  ## local storage. Setting the storageClass attribute to "-" disables dynamic
  ## provisioning of Persistent Volumes; leaving it unset will invoke the default
  ## provisioner.
  persistentVolume:
    enabled: false
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: ""

  ## The CouchDB image
  image:
    repository: couchdb
    tag: 3.2.1
    pullPolicy: IfNotPresent

  ## Experimental integration with Lucene-powered fulltext search
  enableSearch: true
  searchImage:
    repository: kocolosk/couchdb-search
    tag: 0.2.0
    pullPolicy: IfNotPresent

  initImage:
    repository: busybox
    tag: latest
    pullPolicy: Always

  ## CouchDB is happy to spin up cluster nodes in parallel, but if you encounter
  ## problems you can try setting podManagementPolicy to the StatefulSet default
  ## `OrderedReady`
  podManagementPolicy: Parallel

  ## Optional pod annotations
  annotations: {}

  ## Optional tolerations
  tolerations: []

  affinity: {}

  service:
    # annotations:
    enabled: true
    type: ClusterIP
    externalPort: 5984

  ## An Ingress resource can provide name-based virtual hosting and TLS
  ## termination among other things for CouchDB deployments which are accessed
  ## from outside the Kubernetes cluster.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    enabled: false
    hosts:
      - chart-example.local
    path: /
    annotations:
      []
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

  ## Optional resource requests and limits for the CouchDB container
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    {}
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    # limits:
    #  cpu: 56
    #  memory: 256Gi

  ## erlangFlags is a map that is passed to the Erlang VM as flags using the
  ## ERL_FLAGS env. `name` and `setcookie` flags are minimally required to
  ## establish connectivity between cluster nodes.
  ## ref: http://erlang.org/doc/man/erl.html#init_flags
  erlangFlags:
    name: couchdb
    setcookie: monster

  ## couchdbConfig will override default CouchDB configuration settings.
  ## The contents of this map are reformatted into a .ini file laid down
  ## by a ConfigMap object.
  ## ref: http://docs.couchdb.org/en/latest/config/index.html
  couchdbConfig:
    couchdb:
      uuid: budibase-couchdb # REQUIRED: Unique identifier for this CouchDB server instance
    # cluster:
    #   q: 8 # Create 8 shards for each database
    chttpd:
      bind_address: any
      # chttpd.require_valid_user disables all the anonymous requests to the port
      # 5984 when is set to true.
      require_valid_user: false

  # Kubernetes local cluster domain.
  # This is used to generate FQDNs for peers when joining the CouchDB cluster.
  dns:
    clusterDomainSuffix: cluster.local

  ## Configure liveness and readiness probe values
  ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
```
