### DISCUSSION TITLE
How to get real client ip in docker？

### DISCUSSION THREAD

**Discussion by zhengtulymGh** [Budibase/budibase#8507] [Help]
I have deployed Budibase using Docker and Docker Compose locally. But I can't get the real client ip by `ctx.headers["x-forwarded-for"] || ctx["request"]["ip"]`.

I have proxy configuration in the nginx conf file.

.generated-nginx.dev.conf
```
server { 
    listen       10000 default_server;
    server_name  _;

    location /api/ {
      proxy_read_timeout 120s;
      proxy_connect_timeout 120s;
      proxy_send_timeout 120s; 

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      
      proxy_pass      http://host.docker.internal:4001;
    }
```

docker-compose.yaml
```
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  proxy-service:
    container_name: budi-nginx-dev
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./.generated-nginx.dev.conf:/etc/nginx/nginx.conf
      - ./proxy/error.html:/usr/share/nginx/html/error.html
    ports:
      - "${MAIN_PORT}:10000"
    depends_on:
      - minio-service
      - couchdb-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
