### DISCUSSION TITLE
K8S Helm: Recommended resource requests and limits for services

### DISCUSSION THREAD

**Discussion by vaibhav-goyal** [Budibase/budibase#8895] [Help]
I hosted Budibase on AWS EKS with default values in the chart, but I see app service, worker service, and CouchDB service have frequent restarts. 

If anyone has any recommendations on resource requests and limits that should be set on service, please comment

```yaml
apps:
    logLevel: info
    port: 4002
    replicaCount: 2
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
```

**Comment by melohagan** [comment]
Hey @vaibhav-goyal 

Do you see any error logs in any of these services?

**Reply by vaibhav-goyal** [reply]
Hi @melohagan 
I used the default chart values with no resource requests and limits. I did not monitor the logs but noticed frequent Pods' restarts. 
I have since set the following resource requests and limits and have noticed fewer restarts. 
If there is a general recommendation it would really help. 

App and Worker Service 
```yaml
resources:
      limits:
        cpu: 750m
        memory: 750Mi
      requests:
        cpu: 500m
        memory: 500Mi
```

Proxy Service
```yaml
resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 250m
        memory: 500Mi
```

Redis Service
```yaml
resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 250m
        memory: 500Mi
```

Minio Service
```yaml
resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 250m
        memory: 500Mi
```

CouchDb
```yaml
    resources:
      limits:
        cpu: 750m
        memory: 1500Mi
      requests:
        cpu: 500m
        memory: 1000Mi
```
