### DISCUSSION TITLE
Docker (budibase/budibase): Query Error: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".

### DISCUSSION THREAD

**Discussion by everettmorgan** [Budibase/budibase#8926] [Help] [answered]
Unable to query external REST resources (e.g. httpbin) because Budibase interprets the `GLOBAL_AGENT_HTTPS_PROXY` envar as `GLOBAL_AGENT.HTTP_PROXY` internally, which results in the following error: `Query Error: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".`

<img width="1202" alt="Screen Shot 2022-12-04 at 10 58 11 AM" src="https://user-images.githubusercontent.com/43584788/205509897-e279c6d2-cfc4-4bba-9cac-962f2f424d96.png">

Am I missing something here? Why is Budibase forcing me to use an HTTP URL for the HTTPS proxy? 

Here's my docker-compose file:
```yaml
budibase:
  image: budibase/budibase:latest
  container_name: budibase
  depends_on:
    - minio
  restart: always
  networks:
    - nginx
    - budibase
  environment:
    GLOBAL_AGENT_NO_PROXY: "budibase,minio,nginx,postgres,localhost"
    GLOBAL_AGENT_HTTP_PROXY: http://nginx
    GLOBAL_AGENT_HTTPS_PROXY: https://nginx
    INTERNAL_API_KEY: "${BUDIBASE_API_KEY}"
    JWT_SECRET: "${BUDIBASE_JWT_SECRET}"
    MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
    MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    REDIS_PASSWORD: "${BUDIBASE_REDIS_PASS}"
    COUCHDB_USER: "${COUCHDB_USER}"
    COUCHDB_PASSWORD: "${COUCHDB_PASS}"
  volumes:
    - ./budibase:/data
```
