### DISCUSSION TITLE
Can not access minio

### DISCUSSION THREAD

**Discussion by muksidin** [Budibase/budibase#9089] [Help]
Hi... i install budibase as self hosted.
I want to access minio with this instruction https://docs.budibase.com/docs/accessing-minio, but direct to url `http://127.0.0.1:34385/`. What's wrong?

**Comment by melohagan** [comment]
Hey @muksidin 

Did you forward the port and enable the minio browser as per the docs page?

**Reply by muksidin** [reply]
No i do not forward the port. i have already read the docs how to access minio from this link [https://docs.budibase.com/docs/accessing-minio](url), but i still not understand because i use Budibase as single image docker.

**Comment by melohagan** [comment]
Hey @muksidin 

In the most recent release **2.2.15** we have made the minio port available for single image: https://github.com/Budibase/budibase/commit/ecccadc56c55a8e2d9ced813d8d8474029475db6

Hopefully you should be able to get that to work after pulling the latest image. 

You just need to expose port 9001 when running (either method): https://docs.budibase.com/docs/docker

For example via docker-compose, 

```yaml
services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "8080:80"
      - "9001:9001"
```
