### DISCUSSION TITLE
How can I change CSP setting?

### DISCUSSION THREAD

**Discussion by dannyshin76** [Budibase/budibase#9121] [Help]
(I use a local installation of Budibase)
When I try to make an API call to my backend in the app (not using Budibase API proxy), I am getting the following error in the web browser console:
`because it violates the following Content Security Policy directive: "connect-src 'self'`

My teammate thinks we need a custom setting to "volumes" below in docker-compose.yaml, but it is not working.
```
proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service
    volumes:
      - /home/ec2-user/budibase/bbproxy.nginx.conf:/etc/nginx/templates/nginx.conf.template
```

Could you advise on how to change the CSP setting?
