### DISCUSSION TITLE
BudiBase namespace - Different environments

### DISCUSSION THREAD

**Discussion by fgrande** [Budibase/budibase#9297] [Help]
Hi all,

regarding Kubernetes installation, I'm just wondering if "budibase" is a fixed and mandatory namespace.

I would install different instances (development, staging and prduction), versioning the implementation for collaborative development.

May I deploy budibase with a custom namespace ? 

Then I could copy applications through this, I guess... https://github.com/fabiankaestner/budibase-version-manager 

Regards
FabioG

**Comment by shogunpurple** [comment]
@fgrande - you can now deploy budibase into different namespaces - it's not fixed.

Also that package seems to be unofficial, outdated and not maintained. We now have a public API you can use to manage applications and other resources.

https://docs.budibase.com/reference/post_applications

**Comment by fgrande** [comment]
Thanks for Your answer,

I double checked the APIs, but I can't figure out how to accomplish what I would do.... 

To "copy" an application from an environment to another (let's say from development to staging or from staging to production), I would:

1) export data 
2) import data

Importing data would import connections from the original environment, so should I change them in the export file ? Or should I import the new application and then change connections through API (but I don't see this possibility).

What I'mm trying to figure out is a system that will let me follow an app lifecycle, developing in development environment, the move it into a staging environment and finally in a production environment. All of them will have differente datasources.

Thanks in advance
FabioG

**Reply by shogunpurple** [reply]
I understand you now. We are actually currently working on this feature - the ability to have environment variables per environment (staging, prod) that you can use in your datasources. This would probably allow you to create the workflow you are looking for in a much more lightweight way. This will however be a paid feature.

If that does not suit your needs and you need the ability to migrate between entire budibase installations, this is something that we will support in future but cannot give you a timeline for.

**Reply by fgrande** [reply]
Nice feature, I guess it will be enough for my scopes. 
Thanks for the answer
FabioG

**Comment by fabiofarina** [comment]
Hello we're also trying to deploy budibase in different namespaces but the namespace name is mandatory and fixed as written in the doc page https://docs.budibase.com/docs/kubernetes-k8s#install-budibase-helm-chart

Even changing the Helm release name, the service fqdns considered by the proxy-service deployment still refer to "budibase".

For example, we deployed budibase in the "budibase-preproduction" namespace but in the proxy-service logs we see these

2023/01/11 15:30:44 [error] 26#26: *3 app-service.budibase.svc.cluster.local could not be resolved (3: Host not found), client: 10.42.5.39, ...

It seems that the defaults values about upstreams in values.yml are ignored.

HTH
FabioF

**Reply by shogunpurple** [reply]
Hi @fabiofarina - did you update the proxy upstreams in your configuration?

```
  proxy:
    port: 10000
    replicaCount: 1
    upstreams:
      apps: 'http://app-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns }}:{{ .Values.services.apps.port }}'
      worker: 'http://worker-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns }}:{{ .Values.services.worker.port }}'
      minio: 'http://minio-service.{{ .Release.Namespace }}.svc.{{ .Values.services.dns }}:{{ .Values.services.objectStore.port }}'
      couchdb: 'http://{{ .Release.Name }}-svc-couchdb:{{ .Values.services.couchdb.port }}'
```
