### DISCUSSION TITLE
White page and "Not Found" after Docker restart

### DISCUSSION THREAD

**Discussion by Havock94** [Budibase/budibase#9443] [Help]
Hello, I'm facing an issue after restarting my budibase docker container (docker-compose).
These are the files in my configuration

docker-compose.yaml
```
version: "3"

services:
  budibase:
    container_name: Budibase
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "10000:80"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      COUCHDB_USER: ${COUCH_DB_USER}
      COUCHDB_PASSWORD: ${COUCH_DB_PASSWORD}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    volumes:
      - /volume1/docker/budibase/data:/data
      - /volume1/docker/budibase/plugins:/MyBudibasePlugins
```

.env file
```
MAIN_PORT=10000
COUCH_DB_USER=couchdb
BUDIBASE_ENVIRONMENT=PRODUCTION
PLUGINS_DIR=/MyBudibasePlugins

JWT_SECRET=random_secret
MINIO_ACCESS_KEY=random_secret
MINIO_SECRET_KEY=random_secret
COUCH_DB_PASSWORD=random_secret
REDIS_PASSWORD=random_secret
INTERNAL_API_KEY=random_secret
```

After restarting the container, as soon as I access `http://myurl:10000` I face a white screen with the "Not Found" message.

The only logs I find in the container are

```
127.0.0.1 - - [25/Jan/2023:13:54:39 +0000] "GET / HTTP/1.1" 404 9 "-" "curl/7.74.0" "-"

[notice] 2023-01-25T13:54:39.889977Z couchdb@127.0.0.1 <0.28860.1> 2bdf17ebab localhost:5984 127.0.0.1 undefined GET / 200 ok 1

- - [25/Jan/2023:13:54:48 +0000] "GET /favicon.ico HTTP/1.1" 403 273 "http://myurl:10000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-"
```

I tried to copy the docker-compose.yaml file, the .env file and the `/volume1/docker/budibase/data` folder on another PC and budibase starts with no problem (I can access localhost:10000 and I get redirected to the builder), so it really looks something's wrong in the first environment, but I can't understand what it is.

In the first environment, I already tried deleting the container and re-creating it, emptying cookies and cache on the browser and even deleting the `/volume1/docker/budibase/data` folder but to no avail.
At this point I hope you can guide me, thank you!
