### DISCUSSION TITLE
Custom Domain with Contour Ingress Controller ends with "Failed to load the Budibase client"

### DISCUSSION THREAD

**Discussion by rooso** [Budibase/budibase#9997] [Help]
Hi guys

We do have a self-hosted bb environment on Kubernetes. I want to configure a custom domain for an published app `App01` in bb.

The thread  https://github.com/Budibase/budibase/discussions/1742 says custom domains for apps are supported for self-hosted deployments, and should be implemented using a reverse proxy.

Our Ingress Controller is Contour. According to the docs, url rewriting ist supported:
https://projectcontour.io/docs/v1.18.0/config/request-rewriting/

I did create an HTTPProxy item with the following specs:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/tls-cert-namespace: contour
  name: app-customdomain
spec:
  virtualhost:
    fqdn: app01.company.io
    tls:
      secretName: contour/tls-company-io
  routes:
    - services:
        - name: proxy-service
          port: 10000
      pathRewritePolicy:
        replacePrefix:
        - prefix: /
          replacement: /app/app01
```

This always ends up with the error `Failed to load the Budibase client` in the Developer Console in Edge and the error:
![image](https://user-images.githubusercontent.com/51026046/224675233-474a6824-88e5-4a94-a841-248b58893058.png)

Does someone has a similar deployment done or any ideas why my one is not successfull? Thanks!
