### ISSUE TITLE
[BUDI-7742] cant save SMTP settings

### ISSUE THREAD

**Issue by Freundschaft** [Budibase/budibase#12315]
When I try to save my SMTP settings I just receive a 504 gateway timeout after a long time with the source (from inspector) "Houston we have a problem!"

has anyone else faced this issue?

Thanks!

<sub>[BUDI-7742](https://linear.app/budibase/issue/BUDI-7742/cant-save-smtp-settings)</sub>

**Comment by ConorWebb96** [comment]
Hey @Freundschaft,

Can you follow the bug template or a the very least provide reproduction steps?

Closing for now as not enough information.

**Comment by Freundschaft** [comment]
sure, sorry, I am running off the kubernetes helm chart with the following values:

```
globals:
  platformUrl: "https://budibase.xxx.org"
  appVersion: "2.13.3"
ingress:
  nginx: false
couchdb:
  adminUsername: user
  adminPassword: password
```

![budibase_bug](https://github.com/Budibase/budibase/assets/5065616/0a5a5444-6b78-43f7-b8f4-64c06ff7c5af)

Other settings save fine, just the email setting fails
