### ISSUE TITLE
K8S Autoscaler failing with missing requests

### ISSUE THREAD

**Issue by mzac** [Budibase/budibase#12503]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s 
  - Budibase Version:  
  - App Version: 2.13.31 
  - Helm Chart: 3.0.1
  - AKS Prometheus installed in cluster

**Describe the bug**
When trying to add the Horizontal Pod Autoscaler it fails as it says that the deployments are missing requests as cpu and memory requests are missing from the deployments.

**To Reproduce**

```yaml
services:
  apps:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
  proxy:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
  worker:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
```

**Expected behavior**
It should work

**Screenshots**
  
![image](https://github.com/Budibase/budibase/assets/10270879/94d81750-5f78-48fe-98e1-24d5e1811948)

**Additional context**
We are running Budibase in AKS

**Comment by samwho** [comment]
Hey @mzac, sorry for the delay on getting back to you here.

Each of the `apps`, `proxy`, and `worker` blocks accepts a `resources` key that you can use to set your CPU resources. Here's an example that builds on yours:

```yaml
services:
  apps:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: 300m
  proxy:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: 300m
  worker:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: 300m
```

By default we don't set resources because it's going to be something that differs from installation to installation.

I'm going to close this out, but please feel free to reopen if you're still having problems!
