### ISSUE TITLE
 Issue Installing Budibase with Helm Chart and Existing CouchDB Cluster - `user` and `password` Not Integrated

### ISSUE THREAD

**Issue by nilsonfh** [Budibase/budibase#13760]
**Description**:
I encountered a problem while installing Budibase using the Helm chart when attempting to connect it to an existing CouchDB cluster. The installation fails because the `user` and `password` parameters are not being integrated into the deployment of the Budibase containers when `couchdb.enabled` is set to `false`.

**Steps to Reproduce**:
1. Set up an existing CouchDB cluster.
2. Configure the Helm chart to use the existing CouchDB instance with the following YAML values:
   ```yaml
   services:
     couchdb:
       enabled: false
       url: "http://mycouch.io:1234"
       user: "couchuser"
       password: "couchpassword"
   ```
3. Run the Helm install command: `helm install my-budibase budibase/budibase -f values.yaml`.
4. Observe that the `user` and `password` parameters are not being used in the deployment, leading to connection issues.

**Expected Behavior**:
Budibase should successfully connect to the existing CouchDB cluster using the provided `user` and `password` parameters and complete the installation process.

**Actual Behavior**:
The installation fails because the `user` and `password` parameters are not being integrated into the deployment, resulting in CouchDB connection errors.

**Additional Context**:
- I reviewed the chart template and found that the containers do not integrate the `user` and `password` values when `couchdb.enabled` is set to `false`.
- Specifically, line 45 of the `app-service-deployment.yaml` template file does not account for these parameters:
  ```yaml
  # app-service-deployment.yaml
  # Line 45
          {{ if .Values.services.couchdb.enabled }}
        - name: COUCH_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "couchdb.fullname" . }}
              key: adminUsername
        - name: COUCH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "couchdb.fullname" . }}
              key: adminPassword
        {{ end }}
  ```
