### ISSUE TITLE
Allow HELM value to be provided as `secretRef`

### ISSUE THREAD

**Issue by bdsoha** [Budibase/budibase#14310]
**Describe the feature request**

Some HELM values are considered sensitive *(i.e. `apiEncryptionKey`, `jwtSecret`, `smtp.password`, etc.)*.
Therefore, there should be an option to provide those values as `secretRef`:

#### Example

```yaml
globals:
  apiEncryptionKey:
    valueFrom:
      secretKeyRef:
        name: budibase-secrets
        key: api-encryption
```
