### ISSUE TITLE
Add the ability to set the Nginx resolver in bbproxy image as an environment variable

### ISSUE THREAD

**Issue by oleksandrborniak** [Budibase/budibase#15579]
**Describe the feature request**
bbproxy image has hardcoded "resolver" value in /etc/nginx/nginx.conf and /etc/nginx/templates/nginx.conf.template files.
Please add the ability to set a custom resolver value in /etc/nginx/nginx.conf bbproxy image if it is specified in env.

```
# grep -H -r -i resolv /etc/
/etc/nginx/nginx.conf:  resolver 127.0.0.11 valid=10s ipv6=off;
/etc/nginx/templates/nginx.conf.template:  resolver 127.0.0.11 valid=10s ipv6=off;
#
```

Why it is needed:
When you run Budibase using "podman compose up" command, resolver address 127.0.0.1 does not work

```
bbproxy               | 2025/02/19 10:35:27 [error] 22#22: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
bbproxy               | 2025/02/19 10:35:32 [error] 22#22: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
bbproxy               | 2025/02/19 10:35:37 [error] 22#22: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
```
The resolver address should be the same as the gateway address in the Podman network.

```
root@aborniakFC:~# podman inspect --format '{{json .NetworkSettings.Networks}}' bbproxy | jq .
{
  "deploy_budibase_budibase-network": {
    "EndpointID": "",
    "Gateway": "10.89.5.1",
    "IPAddress": "10.89.5.18",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "ae:43:97:dd:54:22",
    "NetworkID": "deploy_budibase_budibase-network",
    "DriverOpts": null,
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "bbproxy",
      "proxy-service",
      "80c27635e702"
    ]
  }
}
root@aborniakFC:~#
```
In this example, it should be 10.89.5.1.

Can we dynamically set the resolver value the same way us we do it for PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND and PROXY_RATE_LIMIT_API_PER_SECOND environment variables?

Part of docker-compose.yaml file:

```
  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service
    networks:
      - budibase-network
```

Inside bbproxy docker container:

```
# grep -H -r PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND /etc/
/etc/nginx/templates/nginx.conf.template:  limit_req_zone $binary_remote_addr zone=webhooks:10m rate=${PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND}r/s;
# grep -H -r PROXY_RATE_LIMIT_API_PER_SECOND /etc/
/etc/nginx/templates/nginx.conf.template:  limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=${PROXY_RATE_LIMIT_API_PER_SECOND}r/s;
#
```
