### ISSUE TITLE
CouchDB: No matching manifest for linux/arm64/v8 in the manifest list entries (Apple Silicon M1)

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#1828]
**Describe the bug**

CouchDB does not yet support ARM64 Architecture. 

```
Budibase Error
Pulling couchdb-service (ibmcom/couchdb3:)...
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**To Reproduce**
- Install budibase on an ARM64 architecture
- Run the start command:
```
budo hosting --start
```

**Expected behavior**
Budibase will start successfully

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Chip: Apple M1

**Comment by Rory-Powell** [comment]
Workaround is to update `docker-compose.yaml` to include ` platform: linux/amd64` for `couchdb-service`, e.g. 
```yaml
  couchdb-service:
    restart: always
    image: ibmcom/couchdb3
    platform: linux/amd64
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    ports:
      - "${COUCH_DB_PORT}:5984"
    volumes:
      - couchdb3_data:/opt/couchdb/data
```
