### ISSUE TITLE
Watchtower service in docker-compose.yaml does not have port override via .env

### ISSUE THREAD

**Issue by truekonrads** [Budibase/budibase#2421]
**Describe the bug**
In .env file there are facilities to override default ports for services. No such override has been created for watchtower-service

**To Reproduce**
budi hosting --init
examine the docker-compose.yaml and .env

**Expected behavior**
watchtower-service port can be overriden using .env

**Comment by shogunpurple** [comment]
Thanks @truekonrads - watchtower runs on port 8080 so you could update your `docker-compose.yaml` to override the port in the meantime:

```
watchtower:
    image: containrrr/watchtower
    ports:
       - <whatever>:8080
    restart: always
    container_name: watchtower
    command: bbapps bbworker  --interval 60
```

I've created a PR that will allow you to do this 👍 

https://github.com/Budibase/budibase/pull/2422
