### ISSUE TITLE
Data Provider Sort not applied

### ISSUE THREAD

**Issue by pierredewilde** [Budibase/budibase#3150]
1. go to https://docs.budibase.com/quickstart-tutorials/crud-app-with-sql/creating-a-list-screen-from-scratch-using-a-sql-table
2. on step 6: set Service Log Data Provider `Sort Column` to **ServiceDate** and `Sort Order` to **Descending**
3. Service Log Table list remains unsorted

tested with Chrome 95 on macOS 10.15.7

**Comment by jochumdev** [comment]
This is still relevant for me, I don't want my Data Stored in CouchDB.

My Setup:

budibase: v2.7.11
postgresql: 14.8

## local dev .env
```bash
# Version
BUDIBASE_VERSION=v2.7.11
POSTGRES_VERSION=14.8

# Use the main port in the builder for your self hosting URL, e.g. localhost:10000
MAIN_PORT=10000

# This section contains all secrets pertaining to the system
# These should be updated
API_ENCRYPTION_KEY=nAgMVuuCzTzsWzeVhbVRpVbi7CbzMu
JWT_SECRET=zMLrHdyVYwAeJudsPuaf7JVbijxEdP
MINIO_ACCESS_KEY=budibase
MINIO_SECRET_KEY=eErtdVTp4VuEmLmgruXgrgu4b7mKsE
COUCH_DB_PASSWORD=3yTXimVYpbhrhz37mtFUaH3Herovkm
COUCH_DB_USER=budibase
REDIS_PASSWORD=HtqHqzUVWkTnyckyVYEegPULkpV3WH
INTERNAL_API_KEY=EnFNXvmrrhpEpLPWFsJk9cf7V7LA7i

# This section contains variables that do not need to be altered under normal circumstances
APP_PORT=4002
WORKER_PORT=4003
MINIO_PORT=4004
COUCH_DB_PORT=4005
REDIS_PORT=6379
WATCHTOWER_PORT=6161
BUDIBASE_ENVIRONMENT=PRODUCTION
SQL_MAX_ROWS=

# An admin user can be automatically created initially if these are set
BB_ADMIN_USER_EMAIL=
BB_ADMIN_USER_PASSWORD=

# A path that is watched for plugin bundles. Any bundles found are imported automatically/
PLUGINS_DIR=

# Postgres extension
POSTGRES_USER=budibase
POSTGRES_PASSWORD=v9JbrfJYsJqVveMseziCg4UkWrLPvU
PGADMIN_DEFAULT_EMAIL=rene@jochum.dev
PGADMIN_DEFAULT_PASSWORD=doJnJ9vH3rLPanCKTE4yyv7kNdhmfX
```

## docker-compose.yaml

```yaml
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase/apps:${BUDIBASE_VERSION}
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      PLUGINS_DIR: ${PLUGINS_DIR}
    depends_on:
      - worker-service
      - redis-service
    volumes:
      - ./volumes/bbapps_plugins:/plugins

  worker-service:
    restart: unless-stopped
    image: budibase/worker:${BUDIBASE_VERSION}
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couchdb-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - ./volumes/minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    image: budibase/proxy:${BUDIBASE_VERSION}
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
      - APPS_UPSTREAM_URL=http://app-service:4002
      - WORKER_UPSTREAM_URL=http://worker-service:4003
      - MINIO_UPSTREAM_URL=http://minio-service:9000
      - COUCHDB_UPSTREAM_URL=http://couchdb-service:5984
      - WATCHTOWER_UPSTREAM_URL=http://watchtower-service:8080
      - RESOLVER=127.0.0.11
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - ./volumes/couchdb3_data:/opt/couchdb/data

  couchdb-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./volumes/redis_data:/data

  postgres-service:
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data

  pgadmin-service:
    restart: unless-stopped
    image: dpage/pgadmin4:7.3
    ports:
      - "8686:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin_data:/var/lib/pgadmin:rw
    depends_on:
      - postgres-service
```
