### ISSUE TITLE
Helm chart on AWS EKS with ALB ingress: can't access budibase

### ISSUE THREAD

**Issue by greg-mcnamara** [Budibase/budibase#4674]
**Describe the bug**
I installed Budibase on an AWS EKS cluster using the helm chart. When the install is finished the notes output does not show the IP/URL. I can find 2 ingress entries:

```
NAME                CLASS    HOSTS   ADDRESS                                                                       PORTS   AGE
budibase-budibase   <none>   *       k8s-packwise-budibase-[hidden].ap-southeast-2.elb.amazonaws.com   80      17s
ingress-budibase    <none>   *       k8s-packwise-ingressb-[hidden].ap-southeast-2.elb.amazonaws.com   80      17s
```

I tried accessing both addresses but get a 502 gateway error (below that is says "nginx").

Here's my config. I couldn't find any documentation for this so I just had a crack at the settings, please advise if these need to change.

```
ingress:
  enabled: true
  aws: true
  nginx: false
  certificateArn: ""
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: # change if using custom domain
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: 10000
```
**To Reproduce**
1. Cloned helm chart
2. Updated ingress config as shown above
3. Installed helm chart on cluster
4. Tried to access using the ingress addresses generated
5. Access failed with 502 gateway error

**Expected behavior**
Expected one of the ingress addresses to go to the budibase login screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 98.0.1108.56

**Additional context**
