### ISSUE TITLE
k8s helm deploy fails with CreateContainerConfigError: container has runAsNonRoot and image will run as root 

### ISSUE THREAD

**Issue by rogermyung** [Budibase/budibase#4796]
**Describe the bug**
I am trying to deploy budibase to a kubernetes cluster using the helm chart.
The couchdb pod comes up right away, but the other pods: app-service, minio-service, proxy-service, redis-service and worker-service all fail to start up, with errors like

> CreateContainerConfigError: container has runAsNonRoot and image will run as root (pod: "app-service-5cfbb779c7-vfkx8_budibase(b5b3cee7-47e0-4922-8dcb-12bdbc448f5f)", container: bbapps)

I've tried setting the podSecurityContext and securityContext in my values.yaml:
```
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 2000  
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
```
but I didn't see any change.  Using helm template, I didn't see either securityContext propagated to any of the actual services.

I am running kubernetes on AWS EKS, managed by Rancher.(this is my company's kubernetes policy)
