### ISSUE TITLE
Localhost refused

### ISSUE THREAD

**Issue by frehrarri** [Budibase/budibase#5132]
I'm trying to run Budibase through Docker and am unable to connect to the localhost:80 after setup and i'm unsure why.
My Docker containers are running linux/amd64.

**budi hosting --start**
```
Starting services, this may take a moment - first time this may take a few minutes to download images.
Recreating frehrml_redis-service_1 ...
Recreating frehrml_redis-service_1   ... done
Recreating frehrml_minio-service_1   ... done
Recreating frehrml_couchdb-service_1 ... done
Recreating frehrml_couch-init_1      ... done
Recreating bbworker                  ... done
Recreating bbapps                    ... done
bbproxy is up-to-date
Services started, please go to http://localhost:80 for next steps.
```

**docker ps**
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                   PORTS                                             NAMES
ff99c5ba7b12   budibase.docker.scarf.sh/budibase/apps     "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes             4001/tcp                                          bbapps
5aa5aa76456b   budibase.docker.scarf.sh/budibase/worker   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes             4001/tcp                                          bbworker
0cd5aba682de   minio/minio                                "/usr/bin/docker-ent…"   7 minutes ago   Up 7 minutes (healthy)   9000/tcp                                          frehrml_minio-service_1
b9e57a9aa7e4   redis                                      "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes             6379/tcp                                          frehrml_redis-service_1
60d5a50d4596   ibmcom/couchdb3                            "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes             4369/tcp, 5984/tcp, 9100/tcp                      frehrml_couchdb-service_1
cc759fe5dd55   budibase/proxy                             "/docker-entrypoint.…"   2 hours ago     Up 2 hours               80/tcp, 0.0.0.0:80->10000/tcp, :::80->10000/tcp   bbproxy
63adbbed32cd   containrrr/watchtower                      "/watchtower --debug…"   2 hours ago     Up 2 hours               8080/tcp                                          frehrml_watchtower-service_1
```

**docker-compose.yaml**
```
services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    platform: linux/amd64
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```
