### ISSUE TITLE
Can't configure public apps/pages on k8s 

### ISSUE THREAD

**Issue by lsoica** [Budibase/budibase#5321]
What I've tried: 

- Setting public access level for data sources
- Setting public access level for screens

If I open the app in a browser where I am not authenticated, I get:
```
{"message":"Database does not exist.","status":404}
```

_Originally posted by @lsoica in https://github.com/Budibase/budibase/discussions/4805_

**Comment by Bytelegion** [comment]
Any updates for above issue.

**Comment by lsoica** [comment]
Works for me with latest versions. I must add that upgrade didn't work so I had to export, clean install and import apps.

**Comment by Rory-Powell** [comment]
@Bytelegion sorry to hear you're seeing this issue, it's not something we've been able to replicate in any environment. 
I'd recommend trying the import/export that worked for @lsoica. If that does work for you I'd be really grateful if you could edit your original broken app to remove any sensitive data, re-export and send it to support@budibase.com with the title `Issue 5321 - export`. We can import it directly into the database as is and bypass some of the import logic to debug what is broken.

**Comment by Bytelegion** [comment]
@lsoica can you please share your k8s values so that i can match with our values.

These are my values files which we are using.

https://github.com/Budibase/budibase/discussions/5602

**Comment by lsoica** [comment]
Sure, here it is:
```
ingress:
  enabled: true
  aws: false
  nginx: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: <my nginx controller class here>
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts:
    - host: apps.<my domain>
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: 10000
  tls:
    - secretName: kubessl
      hosts:
       - apps.<my domain>
couchdb:
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: "hostpath"
globals:
  appVersion: v1.0.144

```
