### ISSUE TITLE
Importing an app over 1mb fails with 413

### ISSUE THREAD

**Issue by phil-lange** [Budibase/budibase#5952]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 1.0.158

**Describe the bug**
If I try to upload an exported app with a size of over 1MB, I can't upload it anymore because the upload is denied with a 413 error.

**To Reproduce**
1. Export an app with the size of over 1 mb 
2. Try to upload the exported txt
3. See error.

**Comment by shogunpurple** [comment]
Hi @phil-lange - seems like an NGINX error.

Have you edited the `nginx.conf` in `proxy-service` in any way? Or do you have a reverse proxy in front of budibase for a custom domain or anything?

**Comment by phil-lange** [comment]
Yeah, it's an nginx error. We don't have any proxies in front.
https://github.com/Budibase/budibase/blob/develop/hosting/nginx.prod.conf.hbs Line 42 might cause it?
```
  server {
    listen       10000 default_server;
    listen  [::]:10000 default_server;
    server_name  _;
    client_max_body_size 1000m;
```

**Comment by shogunpurple** [comment]
@phil-lange - that looks good to me,`1000m` (1GB) - I'll dig into it - and see if I can recreate. If it doesn't contain sensitive data is it possible for you to share your app export with `support@budibase.com`? Thanks!

**Comment by phil-lange** [comment]
yeah, sorry, I misread that. I sent it to the email you've mentioned, thanks!

**Comment by phil-lange** [comment]
Any news on that?

**Comment by phil-lange** [comment]
r

**Comment by shogunpurple** [comment]
@phil-lange - is this one now resolved?

**Comment by watch-dog-mm** [comment]
Hi @shogunpurple 
I am encountering the same issue as @phil-lange . 

For me I am using Buddibase Version **2.2.9**
and using `budibase/proxy` image. 

My Proxy config is the same is this 
https://github.com/Budibase/budibase/blob/v2.2.9/hosting/nginx.prod.conf.hbs 

Even though I change the nginx proxy config client_max_body_size 1000M on `http` context and  `server` context, it is still showing an error.

```
 http {
  # other config from above file

  client_header_buffer_size 1k;
  client_max_body_size 1000M;
 
  map $http_upgrade $connection_upgrade {
    default     "upgrade";
  }

  server {

    client_max_body_size 1000M;
    ignore_invalid_headers off;
    proxy_buffering off;
     # other configs from above file
    }
}    
```

my docker compose file for proxy is as follow

```
  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    volumes:
      - ./proxy-conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service
```

Thank you very much for your help.
