### ISSUE TITLE
Errors when hosting with Docker and Traefik (`Only absolute URLs are supported`)

### ISSUE THREAD

**Issue by dlford** [Budibase/budibase#6180]
**Hosting**

- Self
  - Method: Docker
  - Budibase Version: 1.0.194

**Describe the bug**
Cannot do anything without error messages, create an app, delete an app, etc.

**To Reproduce**
1. Set up with Docker compose file (https://raw.githubusercontent.com/Budibase/budibase/develop/hosting/docker-compose.yaml)
2. Change Docker compose file only to add Traefik labels
3. Try to use the app

**Expected behavior**
It works without errors

**Screenshots**
![ksnip_20220602-183050](https://user-images.githubusercontent.com/22881850/171770436-f615c700-958b-43d3-8118-611c4bca4acf.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version 101

**Additional context**

Traefik labels:

```yaml
          labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.bbproxy.compress=true"
            - "traefik.http.services.bbproxy.loadbalancer.server.scheme=http"
            - "traefik.http.services.bbproxy.loadbalancer.server.port=10000"
            - "traefik.http.routers.bbproxy.rule=Host(`DOMAIN_REDACTED`)"
            - "traefik.http.routers.bbproxy.entrypoints=https"
            - "traefik.http.routers.bbproxy.tls=true"
            - "traefik.http.routers.bbproxy.tls.certresolver=letsencrypt"
            - "traefik.http.routers.bbproxy.middlewares=bbproxy"
```
Traefik config:

```yaml
providers:
  docker:
    exposedbydefault: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
    forwardedHeaders:
     trustedIPs:
       - "127.0.0.1/32"
       - "172.16.0.0/12"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "EMAIL_REDACTED"
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http
```
