### ISSUE TITLE
App container keeps restarting when connecting through proxy

### ISSUE THREAD

**Issue by rolandwang19** [Budibase/budibase#7051]
I'm using Budibase on a Centos7 server and am trying to connect to the corporate proxy to access the internet. I've set the GLOBAL_AGENT_HTTP_PROXY and GLOBAL_AGENT_HTTPS_PROXY in my docker-compose file under environment like below.

```
services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
    depends_on:
      - worker-service
      - redis-service

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      GLOBAL_AGENT_HTTP_PROXY: http://10.121.80.116:8080
      GLOBAL_AGENT_HTTPS_PROXY: http://10.121.80.116:8080
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init
```

When it runs, I saw that my app container is stuck as restarting and doesn't actually run. I checked the log for the container and found the following.

```
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.32s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.10s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.38s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.07s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.07s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.12s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.06s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.10s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.25s.
yarn run v1.22.19
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
Checking migrations
FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
[Tenant: default] [Migration: user_email_view_casing] [DB: global-db] Error:  FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
bb-alert: Error performing migrations. Exiting. : {"message":"invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0","type":"invalid-json","stack":"FetchError: invalid json response body at http://couchdb-service:5984/global-db/ reason: Unexpected token < in JSON at position 0\n    at /app/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}
Server Closed
Done in 3.19s.
```

The container is able to start when the proxy variables are not set. Only see this when they are. If I try to access the app while it's in this state, I get a 502 error.

![image](https://user-images.githubusercontent.com/10952866/182517654-3e3a4133-340b-4c8b-bc5a-c971c9234286.png)
