### ISSUE TITLE
MinIO env deprecated

### ISSUE THREAD

**Issue by ghost** [Budibase/budibase#7518]
**Hosting**

- Self
  - Method: podman 
  - Budibase Version: latest
  - App Version: latest 

**Describe the bug**
MinIO set ```MINIO_ACCESS_KEY``` and ```MINIO_SECRET_KEY``` deprecated and the new names are ```MINIO_ROOT_USER``` and ```MINIO_ROOT_PASSWORD```

**To Reproduce**
1. Look at the MinIO logs or release notes

**Expected behavior**
No deprecation notice in MinIO logs.

**Screenshots**
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
```

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: RockyLinux 9.0
 - Browser 
 - Version latest

**Additional context**

**Comment by J4NS-R** [comment]
I can confirm this is still an issue with the latest version of minio and this chart.

Workaround: Manually edit the minio `Deployment` with the two required environment variables.

If you're using argo, add this manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-service
  namespace: budibase
spec:
  template:
    spec:
      containers:
        - name: minio-service
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: budibase-budibase
                  key: objectStoreAccess
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budibase-budibase
                  key: objectStoreSecret
```

And then sync with Server-Side Apply. This will add on the two required environment variables without changing anything else of the Deployment. Here is how I configured the `Application`:

```yaml
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
```
