### ISSUE TITLE
Minio fails to start on ARM64

### ISSUE THREAD

**Issue by MarioGK** [Budibase/budibase#8079]
**Hosting**

- Self
  - Method: docker-compose
  - Budibase Version: latest
  - Image: https://hub.docker.com/r/budibase/budibase

**Describe the bug**
On arm64 minio fails to start
```
budibase_1  | /runner.sh: line 70: /minio/minio: cannot execute binary file: Exec format error
```

**To Reproduce**
Use the provided docker-compose.yaml file and run docker-compose up on an arm64 machine

**Comment by melohagan** [comment]
Hi @MarioGK 

Can you try adding `platform: linux/amd64` under the **minio-service** in the docker-compose file.

**Comment by MarioGK** [comment]
Hey @melohagan Thanks for trying to help, i tried to add it to the service but i am getting an error

docker-compose.yaml
```yaml
version: "3.6"

services:
  budibase:
    platform: linux/amd64
    restart: unless-stopped
    image: budibase/budibase:v2.0.3
    ports:
      - "9101:80"
    volumes:
      - ./data:/data
    environment:
      JWT_SECRET: 123
      MINIO_ACCESS_KEY: 123
      MINIO_ROOT_USER: 123
      MINIO_SECRET_KEY: 123
      MINIO_ROOT_PASSWORD: 123
      REDIS_PASSWORD: 123
      COUCHDB_USER: 123
      COUCHDB_PASSWORD: 13
      INTERNAL_API_KEY: 123
```

Error:
```ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.budibase: 'platform'
```

**Comment by melohagan** [comment]
Oh sorry this is the single image. I don't think the single image supports ARM at the moment @mike12345567

**Comment by shogunpurple** [comment]
@melohagan The single image does support ARM. The `platform` option shouldn't be required. Looks like this might be something that we need to look into. I'll try debugging on my ARM mac.

**Comment by RixzZ** [comment]
Same problem on my RaspberryPi.

Seems like you use [this script](https://github.com/Budibase/budibase/blob/develop/scripts/install-minio.sh) to download the correct version of minio, after checking the TARGETARCH env variable.

If I'm not missing something, o n [the Dockerfile](https://github.com/Budibase/budibase/blob/develop/hosting/single/Dockerfile#L23) for the single container, you seem to have the env variable fixed to 'amd64'.

**Comment by shogunpurple** [comment]
Just after running this, both through docker-compose and through the `docker` command directly and both are working on my ARM mac. The `TARGETARCH` env variable looks like it's hardcoded, but it's not - docker will inject this variable when it runs the multi platform builds using `buildx`. You can see the platforms that we build for in the CI job that creates the single image.

```
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: budibase/budibase,budibase/budibase:v${{ env.RELEASE_VERSION }}
          file: ./hosting/single/Dockerfile
```

The only thing I can think of now could possibly be the fact that the hardware that you are running on is not compatible with the way we are building the images. @MarioGK are you using a Raspberry Pi also?

**Comment by RixzZ** [comment]
Oh okay. Either way, seeing the layers for the image on DockerHub, even the arm64 version shows a few mentions to 'amd64' as TARGETARCH.

- https://hub.docker.com/layers/budibase/budibase/latest/images/sha256-3943440cdbc62e7ce9a7dd771ac10f57a3b2ec0edb1b639a6e4d7d29ac3facfc?context=explore

It's that okay?

**Comment by shogunpurple** [comment]
@RixZ that does seem odd - I just looked at our build and the log lines both say that they are installing the `amd64` versions of both the oracle and ARM packages. But I think this is a function of the emulation since it's working on my mac. On looking, I'm starting to wonder now if we need to compile an image for `arm/v7` now as well. Are you generally able to run `arm64` images on your raspberry Pi? Which Pi do you have?

**Comment by RixzZ** [comment]
Yeah, it's a Raspberry Pi 3 with ARM64. All other docker images I can use on it are 'amd64'.

**Comment by mike12345567** [comment]
I had been trying to setup a Raspberry Pi 4 last night to test this - I believe we probably need to release both an `arm7` and a `arm64` image - I'll try updating this in our build pipeline.

**Comment by MarioGK** [comment]
> Just after running this, both through docker-compose and through the `docker` command directly and both are working on my ARM mac. The `TARGETARCH` env variable looks like it's hardcoded, but it's not - docker will inject this variable when it runs the multi platform builds using `buildx`. You can see the platforms that we build for in the CI job that creates the single image.
> 
> ```
>         with:
>           context: .
>           push: true
>           platforms: linux/amd64,linux/arm64
>           tags: budibase/budibase,budibase/budibase:v${{ env.RELEASE_VERSION }}
>           file: ./hosting/single/Dockerfile
> ```
> 
> The only thing I can think of now could possibly be the fact that the hardware that you are running on is not compatible with the way we are building the images. @MarioGK are you using a Raspberry Pi also?

I am trying to run it on a t4g aws instance, not a raspberry pi

**Comment by brendanvz** [comment]
Also having a problem with minio starting.
I am running on an Oracle Cloud Ampere A1 Compute.
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1016-oracle aarch64)

The logs show the following
` /runner.sh: line 70: /minio/minio: cannot execute binary file: Exec format error`

My docker-compose.yaml, i've tried platform linux/amd64 and linux/arm64
```
services:
  budibase:
    platform: linux/arm64
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - 10000:80
    environment:
      JWT_SECRET: *
      MINIO_ACCESS_KEY: *
      MINIO_SECRET_KEY: *
      REDIS_PASSWORD: *
      COUCHDB_USER: *
      COUCHDB_PASSWORD: *
      INTERNAL_API_KEY: *
    volumes:
      - budibase_data:/data
volumes:
  budibase_data:
    driver: local

```

I also get the "Error creating App" Error.
Browser debug console reveals

`[Builder] HTTP 500 on POST:http://127.0.0.1:10000/api/applications
	Unable to write to object store bucket.`
