### ISSUE TITLE
Error initialising app:Not Found

### ISSUE THREAD

**Issue by Jamessigur** [Budibase/budibase#8138]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: last version

Please help me install using the method from the site via docker-compose.yml:

```
version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "8080:80"
    environment:
      JWT_SECRET: <secret>
      MINIO_ACCESS_KEY: <secret>
      MINIO_SECRET_KEY: <secret>
      REDIS_PASSWORD: <secret>
      COUCHDB_USER: <secret>
      COUCHDB_PASSWORD: <secret>
      INTERNAL_API_KEY: <secret>
    volumes:
      - budibase_data:/data

volumes:
  budibase_data:
    driver: local
```

I created a super admin, I try to create an application and I get an error:

![image](https://user-images.githubusercontent.com/105172391/194059570-a6b77350-e37e-4102-9b12-1e735cde80fb.png)

![image](https://user-images.githubusercontent.com/105172391/194059786-03324121-bee5-408c-98db-4d8b91169c96.png)
