### ISSUE TITLE
Use real couchDB in unit tests

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#8210]
**COS**
- Don't use the couchDB in memory DB for unit tests
- Remove all references to `isTest()` that were relying on the mocked couch (search, replication etc)
- Add the couchDB container to any CI jobs that will be reliant on it
```
    services:
      couchdb:
        image: ibmcom/couchdb3
        env:
          COUCHDB_PASSWORD: budibase
          COUCHDB_USER: budibase
        ports:
          - 4567:5984
```
- Add docker-compose config to be able to spin up an ephemeral couch for unit testing in `server` and `worker`
