### ISSUE TITLE
Use real redis in unit tests and in qa-core

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#8211]
**COS**
- Don't use the redis in memory DB for unit tests
- Remove all references to `isTest()` that were relying on the mocked redis (bull for example)
- Add the redis container to any CI jobs that will be reliant on it
```    
services:
      redis:
        image: redis
        command: redis-server --requirepass budibase
        ports:
          - 6379:6379
```
- Add docker-compose config to be able to spin up an ephemeral redis for unit testing in `server` and `worker`
