### ISSUE TITLE
"budibase-infra" Docker Image with couch, minio and redis

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#8322]
**COS**
- Build and package a docker image with couch, minIO and redis exposed on different ports
- Use this image in `qa-core` and in the budibase unit tests 
- Use in CI using the github actions `services` key
- Remove all references to `isTest()` that were relying on the mocked services (bull, file system minio and pouchdb)
- Use for local dev

```
services:
    bbtest:
      image: budibase/test
      ports:
        - 6379:6379
        - 4567:5984
        - 9001:9001
```
