### ISSUE TITLE
[BUDI-6951] OpenID Connect (OIDC) config in environment variables and Helm chart

### ISSUE THREAD

**Issue by jtv8** [Budibase/budibase#8466]
**Describe the feature request**

When self-hosting Budibase, it would be very helpful to be able to configure the OpenID Connect settings via environment variables, and to be able to set these environment variables from the `values.yaml` of the Helm chart.

This would be useful for orgs that use e.g. Terraform to configure their identity provider apps. The generated client ID and secret could then be injected into the Helm release rather than provided manually later. This would mean that the Budibase deployment is secure as soon as it is available, rather than having to create a superadmin account via the browser.

Example environment variables:

```
OIDC_CONFIG_URL
OIDC_CLIENT_ID
OIDC_CLIENT_SECRET
OIDC_CALLBACK_URL
OIDC_NAME
OIDC_ICON
OIDC_DEFAULT_SUPERADMIN_EMAIL
```

Example `values.yaml` snippet:

```
globals:
  appVersion: "latest"
  ...
  oidc:
    configURL: "https://foo.bar/config"
    callbackURL: "https://foo.bar/callback"
    clientID: "12345678-8765421"
    clientSecret: "8765421-12345678"
    name: "My OpenID Connect"
    icon: "https://foo.bar/icon.png"
    defaultSuperAdminEmail: "admin@foo.co"
```

<sub>[BUDI-6951](https://linear.app/budibase/issue/BUDI-6951/openid-connect-oidc-config-in-environment-variables-and-helm-chart)</sub>
