### ISSUE TITLE
Enable minio browser in single image

### ISSUE THREAD

**Issue by dirathea** [Budibase/budibase#8590]
**Describe the feature request**
 Single BudiBase Docker image for ARM works great. But my cases require access to Minio server inside the container to fetch the file via Minio SDK. I wish we could enable minio browser for this image, but if not, at least allow Minio SDK to access the server.

Right now we can't do any of those actions. When I try to access minio instance via SDK, it throws an error `The request signature we calculated does not match the signature you provided. Check your key and signing method`. According to this issue https://github.com/minio/minio/issues/7936, the configuration lack of `proxy_set_header Host $http_host;` config on the nginx part.

I tried to do it by overriding the nginx config via docker compose, and it work as expected. Shall I raise PR for it?

```yaml
version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:v2.1.15
    environment:
      JWT_SECRET: ${JWT_SECRET}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "10000:80"
    volumes:
      - ./default:/etc/nginx/sites-available/default
      - budibase_data:/data
```

and this is the diff of  `default` file, mostly taken from https://github.com/Budibase/budibase/blob/develop/hosting/single/nginx/nginx-default-site.conf
```diff
git diff default     
diff --git a/default b/default
index 136ec56..4999422 100644
+++ a/default
--- b/default
@@ -79,7 +79,6 @@ server {
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
+        proxy_set_header Host $http_host;
 
         proxy_connect_timeout 300;
         proxy_http_version 1.1;
```

**Screenshots**
