### ISSUE TITLE
App import error from cloud to self-hosted

### ISSUE THREAD

**Issue by KevinHamonApp** [Budibase/budibase#8622]
**Hosting**

- Self
  - Method: docker single image
- Cloud
  - Tenant ID: valo

**Describe the bug**
Hi there ! 
I'm moving an app today from cloud to selfhosting.
I launched the single image Docker on my VPS
Seems to  work perfeclty.
But all my apps imports fail. I keep getting " 🔺 Error creating app "
I tried to update my apps, and same problem.
I tried to create a new app empty on cloud.
But same problem when importing it.
I don't have any clue on what could be the problem ... 
Is this linked to the new release version ? Maybe incompatible with Budibase single image ?
Thanks a lot for your help or thoughts ... 

**To Reproduce**
1. Launch single Budibase docker image lastest
2. Create an app on Cloud
3. Export latest
4. Import in self-hosted account

**Expected behavior**
The app import success.
  
**App Export**
For example, a simple app with this problem : 
[My app-export-1668004830080.tar.gz](https://github.com/Budibase/budibase/files/9972099/My.app-export-1668004830080.tar.gz)

**Desktop (please complete the following information):**
 - OS: Debian 10 for self-hosting

**Comment by melohagan** [comment]
Hey @KevinHamonApp 

I was able to import that app successfully, however there was no content:
![Screenshot 2022-11-10 at 15 04 39](https://user-images.githubusercontent.com/101575380/201129634-ce44e362-31d8-4d70-b071-2de0d21a7427.png)

![Screenshot 2022-11-10 at 15 05 00](https://user-images.githubusercontent.com/101575380/201129816-d5d965ef-9522-4be1-b883-3418c2a91ce2.png)

**Comment by melohagan** [comment]
![Screenshot 2022-11-10 at 15 09 45](https://user-images.githubusercontent.com/101575380/201131953-6a88562d-095c-418b-954a-04a93ebe5709.png)

**Comment by KevinHamonApp** [comment]
Hi there!
I'm still facing this issue. When building the single budibase, and directly importing from cloud, I got an error. 
![image](https://user-images.githubusercontent.com/74555017/204250844-7e9ef525-3bdf-4121-8cbe-48474af46616.png)

In console, I observe this : 
![image](https://user-images.githubusercontent.com/74555017/204250759-a27608a4-86b6-4706-b0f8-4a2c82878eb8.png)

**Comment by melohagan** [comment]
Hey @KevinHamonApp 

I believe that error simply means that the app you are trying to import is too large.

**Comment by KevinHamonApp** [comment]
Thanks for your answer !

Well, the app is almost empty in data
The whole file is under 2,4Mo 
Then this functionnality seems to not be usable ...

**Comment by melohagan** [comment]
Is it the same export that's attached to this issue that you are trying to import? 

> When building the single budibase
Do you mean the docker single image self-hosted?

**Comment by KevinHamonApp** [comment]
Yes it is the same. Here is the file : 
[Test form-export-1669630881194.tar.gz](https://github.com/Budibase/budibase/files/10102707/Test.form-export-1669630881194.tar.gz)

Yes, I'm working with the single image self-hosted. I made sure to pull the last version this morning.

**Comment by KevinHamonApp** [comment]
I precise that I tried Export / import from a self-hosted app with the full docker-compose to a cloud version, it worked all well. 
But in this way I can't make it work ...

**Comment by melohagan** [comment]
I'm struggling to reproduce any error with that export you provided. I'm simply importing it into a single image self-hosted environment
![Screenshot 2022-11-28 at 10 36 59](https://user-images.githubusercontent.com/101575380/204256869-84d26aba-018f-4c28-bbfa-f1f787965cca.png)

**Comment by KevinHamonApp** [comment]
This might be an error from my self-hosting configuration then ... 
The thing is that everything else seems to work properly. App creation / database creation etc ...

**Comment by KevinHamonApp** [comment]
I'm still facing this issue ... Here is more data 
I'm running the image through docker compose, here it is : 
```
version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "8080:80"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    volumes:
      - budibase_data:/data

volumes:
  budibase_data:
    driver: local
```

The whole thing is behind a proxy, here are the basics of my nginx conf, with certbot auto-encrypting ok
````
events {}
http {

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        server_name solutions.ouivalo.fr ouivalo.fr www.ouivalo.fr;
        listen 443 ssl;
        
        ssl_certificate /etc/letsencrypt/live/solutions.ouivalo.fr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/solutions.ouivalo.fr/privkey.pem;
        
        location / {
            proxy_pass 'http://host.docker.internal:8080';
        }
}
}
```

Can't see what's wrong ... I tried purging my docker storage on my server, did the same.
