### ISSUE TITLE
Lost all apps after upgrade (docker compose)

### ISSUE THREAD

**Issue by MrApe** [Budibase/budibase#9390]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker-compose (single image)
  - Budibase Version: 2.2.
  - App Version: <version> 
 
**Describe the bug**
Lost all applications after Upgrading from version 2.2.1 to 2.2.19. All Settings, Accounts and configurations are still there. Even the App numbers on the "Users" page are correct but the app itself seems to have gone.

**To Reproduce**

```shell
docker compose down
docker compose pull
docker compose up
```

**Expected behavior**
The app should still be there.

**Additional context**
All stateful data is mounted into the container, so should be kept between container restarts. Previous upgrades have been successful with the steps above. 
What's the exact architecture of app storage? Maybe it is possible to recover them?

**Comment by shogunpurple** [comment]
@MrApe can you post your `docker-compose.yaml` file please?

**Comment by MrApe** [comment]
@shogunpurple sure! Thanks for helping!

```yaml
version: "3"
services:
  budibase:
    image: budibase/budibase:latest
    restart: unless-stopped
    environment:
      SELF_HOSTED: 1
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ENABLE_ANALYTICS: "false"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_USER: ${COUCHDB_USER}
      PLUGINS_DIR: ${PLUGINS_DIR}
    volumes:
      - /mnt/data/aero-apps-data/plugins:/plugins
      - /mnt/data/aero-apps-data/budibase:/data
    labels:
        [...traefik labels removed...]
```
