### ISSUE TITLE
Portainer Official Template - Error creating app - Error initialising app: Not Found

### ISSUE THREAD

**Issue by camnop** [Budibase/budibase#9457]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Portainer official app template
  - Budibase Version: 2.2.22
  - Portainer IO Community Edition 2.16.2

**Describe the bug**
it is my first time trying to use budibase. When I try to create a app from scratch or an app template, it gives me an error:

![image](https://user-images.githubusercontent.com/4583389/215014736-aeadd79a-2eaa-4ecb-b628-1337ad635e83.png)

**To Reproduce**

https://docs.budibase.com/docs/portainer

Portainer
How to add the template to portainer
Go to Portainer settings
Enter https://raw.githubusercontent.com/Budibase/budibase/master/hosting/portainer/template.json into the app settings URL field, and click save:

![image](https://user-images.githubusercontent.com/4583389/215013579-20bfd6e1-e6b9-4369-abbd-3117dcf349f6.png)

Go to templates, and see that Budibase is now an option

![image](https://user-images.githubusercontent.com/4583389/215013664-dc261176-9760-4d27-8d4e-7fa54428ae71.png)

Install it, inserting new passwords where "change-me" is written:
![image](https://user-images.githubusercontent.com/4583389/215013782-d0e799ea-9e09-4f9c-a6fa-ae45dfa49014.png)

Try to create an scratch app or template app

Error creating app
![image](https://user-images.githubusercontent.com/4583389/215013830-5d9d53c9-8d1a-4368-bd67-9bf93403f049.png)

![image](https://user-images.githubusercontent.com/4583389/215013242-481bb1da-6a3b-45c1-a5d9-1a60598f00cf.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/4583389/215013341-4523880c-1f87-4f33-abce-a2242092e383.png)

![image](https://user-images.githubusercontent.com/4583389/215013886-e5737371-d44f-4ecb-96ea-27461f9ff993.png)

budibase-couch-init-1:
error=file_exists reason=The database could not be created, the file already exists.
![image](https://user-images.githubusercontent.com/4583389/215013935-072478d7-61e4-4424-bc14-f5df5830313c.png)

![image](https://user-images.githubusercontent.com/4583389/215014449-d4d7fdb1-95f1-463f-b534-d1af4b4aa333.png)

  
**App Export**

```
Request URL: http://192.168.0.110:10000/api/applications
Request Method: POST
**Status Code: 500 Internal Server Error**
Remote Address: 192.168.0.110:10000
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 66
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.budibase.net https://cdn.budi.live https://js.intercomcdn.com https://widget.intercom.io; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://rsms.me https://maxcdn.bootstrapcdn.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://*.budibase.net https://api-iam.intercom.io https://api-iam.intercom.io  https://api-ping.intercom.io https://app.posthog.com wss://nexus-websocket-a.intercom.io  wss://nexus-websocket-b.intercom.io https://nexus-websocket-a.intercom.io https://nexus-websocket-b.intercom.io  https://uploads.intercomcdn.com  https://uploads.intercomusercontent.com https://*.s3.amazonaws.com https://*.s3.us-east-2.amazonaws.com https://*.s3.us-east-1.amazonaws.com https://*.s3.us-west-1.amazonaws.com https://*.s3.us-west-2.amazonaws.com https://*.s3.af-south-1.amazonaws.com https://*.s3.ap-east-1.amazonaws.com https://*.s3.ap-southeast-3.amazonaws.com https://*.s3.ap-south-1.amazonaws.com https://*.s3.ap-northeast-3.amazonaws.com https://*.s3.ap-northeast-2.amazonaws.com https://*.s3.ap-southeast-1.amazonaws.com https://*.s3.ap-southeast-2.amazonaws.com https://*.s3.ap-northeast-1.amazonaws.com https://*.s3.ca-central-1.amazonaws.com https://*.s3.cn-north-1.amazonaws.com https://*.s3.cn-northwest-1.amazonaws.com https://*.s3.eu-central-1.amazonaws.com https://*.s3.eu-west-1.amazonaws.com https://*.s3.eu-west-2.amazonaws.com https://*.s3.eu-south-1.amazonaws.com https://*.s3.eu-west-3.amazonaws.com https://*.s3.eu-north-1.amazonaws.com https://*.s3.sa-east-1.amazonaws.com https://*.s3.me-south-1.amazonaws.com https://*.s3.us-gov-east-1.amazonaws.com https://*.s3.us-gov-west-1.amazonaws.com; font-src 'self' data: https://cdn.jsdelivr.net https://fonts.gstatic.com https://rsms.me https://maxcdn.bootstrapcdn.com  https://js.intercomcdn.com  https://fonts.intercomcdn.com; frame-src 'self' https:; img-src http: https: data: blob:; manifest-src 'self'; media-src 'self' https://js.intercomcdn.com; worker-src 'none';
Content-Type: application/json; charset=utf-8
Date: Fri, 27 Jan 2023 05:12:44 GMT
Server: nginx
Vary: Accept-Encoding
x-budibase-tenant-id: default
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 728
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarylvmxWehCSJ3GlNYz
Cookie: budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c18wZGIyM2M1NjI4Yjc0MGU1OTA0YjZkNjVhMGUwNzM2OSIsInNlc3Npb25JZCI6IjA5ZTRmZmNmOTQxZTQ5MWI5N2ViZWI2YWQ2ZDZmNzQ4IiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjc0NzkzODczfQ.G0e2xPHhhVpM_PJN4ATC8UxGoadMBm2dq2SrSgHxYbc; budibase:auth.sig=MHKGOHHQHOmfCXOFO0tDtUys9lo; _pk_id.1.3ee3=304c06553081316f.1674794392.; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFwcF9kZXZfZGQxMWJkMDcyODg0NDNhMGI3ZWM0ZWFkYjdmOThlNTQiLCJpYXQiOjE2NzQ3OTQ4MDl9.aA2rrUthcTZSW2yf0BPuJWDO6MPbHNvMAWd5PZVqOkc; ph_phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU_posthog=%7B%22distinct_id%22%3A%22us_0db23c5628b740e5904b6d65a0e07369%22%2C%22%24device_id%22%3A%22185f16921e28a2-002653318b13ab-26021051-144000-185f16921e3200e%22%2C%22%24user_id%22%3A%22us_0db23c5628b740e5904b6d65a0e07369%22%2C%22%24referrer%22%3A%22%24direct%22%2C%22%24referring_domain%22%3A%22%24direct%22%2C%22%24sesid%22%3A%5B1674792477159%2C%22185f16921e7b79-04369b5de9ffbe-26021051-144000-185f16921e82201%22%2C1674792477159%5D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24enabled_feature_flags%22%3A%7B%7D%7D
DNT: 1
Host: 192.168.0.110:10000
Origin: http://192.168.0.110:10000
Referer: http://192.168.0.110:10000/builder/portal/apps/create
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
x-budibase-api-version: 1
x-budibase-app-id
x-csrf-token: 772db0a8-3396-4a3b-80de-616a32d94451
```

```
version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      PLUGINS_DIR: ${PLUGINS_DIR}
    depends_on:
      - worker-service
      - redis-service
#    volumes:
#      - /some/path/to/plugins:/plugins

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
      - APPS_UPSTREAM_URL=http://app-service:4002
      - WORKER_UPSTREAM_URL=http://worker-service:4003
      - MINIO_UPSTREAM_URL=http://minio-service:9000
      - COUCHDB_UPSTREAM_URL=http://couchdb-service:5984
      - WATCHTOWER_UPSTREAM_URL=http://watchtower-service:8080
      - RESOLVER=127.0.0.11
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

```

**Desktop (please complete the following information):**
 - OS: Debian 11 (using like server) Windows 11 (using like client)
 - Browser Chrome
 - Version  109.0.5414.120

**Additional context**
